<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @author	   cherdchai Hinjumpa , bugcherd@gmail.com   089-003-5240
 * @website   http://magentothai.wordpress.com/
 */
?>
<p><?php echo $this->getMethod()->getTitle().'  '.$this->getPlanText() ?><br/>
<?php
/*
$PaymentSelect = $this->htmlEscape($this->getInfo()->getPoNumber());
$ChannelCode = ""; $ChannelName = "-";
$AgentCode = ""; $AgentName = "-";
$PaymentArray = explode("|",trim($PaymentSelect));
$ChannelCode = $PaymentArray[0];
$AgentCode = $PaymentArray[1];
$_SESSION["ChannelCode"] = $ChannelCode;
$_SESSION["AgentCode"] = $AgentCode;
echo "<p>select code : " . $PaymentSelect . "</p>";
exit;
*/
?>