<?php
    $_productCollection = $this->getLoadedProductCollection();
		$_productCollection->clear();
		$_productCollection->addAttributeToSelect('flip_image');
		$_productCollection->load();
    $_helper            = $this->helper('catalog/output');
    $_collectionSize    = $_productCollection->count();
    $_columnCount       = $this->getColumnCount();
?>
<?php if (!$_collectionSize) : return; endif; ?>
<style>
    .amconf-noimage-div {
        background-color: white;
        border-radius: 0;
        padding: 3px;
    }
    a.amconf-color-container {
        display: inline-block;
        text-align: center;
        text-indent: -9999px;
    }
    dl{
        padding-bottom: 15px;
    }
    .input-box{
        height: 25px;
    }
    a.option_disabled {
        pointer-events: none;
        cursor: default;
        position: relative;
    }
    a.option_disabled:before{
        content: "";
        width: 1px;
        height: 100%;
        position: absolute;
        top: 0px;
        left: 50%;
        transform: rotate( -45deg );-webkit-transform: rotate( -45deg ); -moz-transform: rotate( -45deg );
        background: black;
    }
</style>
<div class="categoryproducts block-highlight <?php echo $this->getClassName() ?>">
    <div class="block-content">
				<div id="bestseller-product-list" class="products-grid">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            <div class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="prolabel-wrapper">
                  <?php echo Mage::helper('amlabel')->getLabels($_product, 'category'); ?>
                    <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
											<?php if ($_product->getFlipImage() != 'no_selection' && $_product->getFlipImage()): ?>	
												<div class="flip-container" ontouchstart="this.classList.toggle('hover');">
													<div class="flipper">
														<div class="front">
															<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(268); ?>"
													alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
											/>
														</div>				 
														<div class="back">
															<img src="<?php echo $this->helper('catalog/image')->init($_product, 'flip_image')->resize(268); ?>"
													alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'flip_image'), null, true) ?>"
											/>
														</div>				 
													</div>				 
												</div>		
											<?php else:?>
												<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(268)?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
											<?php endif ?>
										</a>
                  <?php if ($this->helper('wishlist')->isAllow()) : ?>
                      <a href="<?php if(Mage::helper('customwishlist')->checkItemInWishlist($_product->getId())):?>javascript:void(0)<?php else:?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif ?>" class="link-wishlist <?php if(Mage::helper('customwishlist')->checkItemInWishlist($_product->getId())):?>added-item<?php endif ?>"></a>
                    <?php endif; ?>
                </div>

                <?php if ($_product->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE) : ?>
                    <?php $_attributes = Mage::helper('core')->decorateArray($_product->getTypeInstance(true)->getConfigurableAttributes($_product)) ?>
                    <?php $productAttribute = $this->getAttributeOfConfigProduct($_product); ?>
                    <?php $y = 1; ?>
                    <?php $numberAttributes = count($_attributes);?>
                    <?php foreach ($_attributes as $_attribute): ?>
                        <dl class="<?php echo $_attribute->getProductAttribute()->getAttributeCode() ?>">
                            <dt class="bestsell-customgroup-item-attribute-label"><label
                                    class="required"><?php echo $_attribute->getLabel() ?></label></dt>
                            <div class="input-box bestsell-customgroup-item-attribute-input-box amconf-images-container"
                                 id="bestsell-customgroup-item-<?php echo $_product->getId() ?>-attribute<?php echo $_attribute->getAttributeId() ?>">
                                <?php $config = $productAttribute[$_attribute->getAttributeId()]; ?>
                                <?php $i = count($config['options']);?>
                                <?php foreach ($config['options'] as $value): ?>
                                    <?php $imageOption = $this->getImageOptions($_attribute, $value); ?>
                                    <?php $i = $i - 1; ?>
                                    <?php ?>
                                    <div class="amconf-image-container">
                                        <input type="radio" style="display:none"
                                               name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]"
                                               id="bestsell-customgroup-item-<?php echo $_product->getId() ?>-attribute<?php echo $_attribute->getAttributeId() ?>-<?php echo $value['id'] ?>"
                                               class="validate-required<?php echo $_product->getId(); ?> <?php if ($i == 0): ?>validate-one-required<?php endif; ?>"
                                               value="<?php echo $value['id'] ?>"/>
                                        <?php if (!$imageOption['image'] || $imageOption['color']): ?>
                                            <?php if ($imageOption['color']): ?>
                                                <a
                                                    style="background: #<?php echo $imageOption['color'] ?>;margin-right: -7px; width: <?php echo $imageOption['w'] ?>px; height: <?php echo $imageOption['h'] ?>px; line-height: <?php echo $imageOption['h']?>"
                                                    href="javascript:void(0)"
                                                    class="amconf-color-container customgroup-attribute-option-link <?php if ($y - 1 != 0): ?> option_disabled <?php endif; ?> "
                                                    id="link-bestsell-customgroup-item-<?php echo $_product->getId() ?>-attribute<?php echo $_attribute->getAttributeId() ?>-<?php echo $value['id'] ?>"
                                                    data-id="customgroup-item-<?php echo $_product->getId() ?>-attribute<?php echo $_attribute->getAttributeId() ?>-<?php echo $value['id'] ?>"
                                                    data-name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]"
                                                    data-value="<?php echo $value['id'] ?>"
                                                    data-label="<?php echo $value['label'] ?>"
                                                    onclick="customgroupCheckAttributeBestSell('<?php echo $_product->getId() ?>','<?php echo $_attribute->getAttributeId() ?>','<?php echo $value['id'] ?>', '<?php echo $_attribute->getPosition() ?>','<?php echo $_attribute->getProductAttribute()->getAttributeCode() ?>');">
                                                    <?php echo $value['label'] ?>
                                                </a>
                                            <?php else: ?>
                                                <a
                                                    style="margin-right: -7px; width: <?php echo $imageOption['w'] ? $imageOption['w'] : 29 ?>px; height: <?php echo $imageOption['h'] ? $imageOption['h'] : 29 ?>px; line-height: <?php echo $imageOption['h'] ? $imageOption['h'] : 29 ?>px;"
                                                    href="javascript:void(0)"
                                                    class="amconf-noimage-div customgroup-attribute-option-link <?php if ($y - 1 != 0): ?> option_disabled <?php endif; ?> "
                                                    id="link-bestsell-customgroup-item-<?php echo $_product->getId() ?>-attribute<?php echo $_attribute->getAttributeId() ?>-<?php echo $value['id'] ?>"
                                                    data-id="customgroup-item-<?php echo $_product->getId() ?>-attribute<?php echo $_attribute->getAttributeId() ?>-<?php echo $value['id'] ?>"
                                                    data-name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]"
                                                    data-value="<?php echo $value['id'] ?>"
                                                    data-label="<?php echo $value['label'] ?>"
                                                    onclick="customgroupCheckAttributeBestSell('<?php echo $_product->getId() ?>','<?php echo $_attribute->getAttributeId() ?>','<?php echo $value['id'] ?>', '<?php echo $_attribute->getPosition() ?>','<?php echo $_attribute->getProductAttribute()->getAttributeCode() ?>');">
                                                    <?php echo $value['label'] ?></a>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <a href="javascript:void(0)"
                                               class="customgroup-attribute-option-link <?php if ($y - 1 != 0): ?> option_disabled <?php endif; ?> "
                                               id="link-bestsell-customgroup-item-<?php echo $_product->getId() ?>-attribute<?php echo $_attribute->getAttributeId() ?>-<?php echo $value['id'] ?>"
                                               data-id="customgroup-item-<?php echo $_product->getId() ?>-attribute<?php echo $_attribute->getAttributeId() ?>-<?php echo $value['id'] ?>"
                                               data-name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]"
                                               data-value="<?php echo $value['id'] ?>"
                                               data-label="<?php echo $value['label'] ?>"
                                               onclick="customgroupCheckAttributeBestSell('<?php echo $_product->getId() ?>','<?php echo $_attribute->getAttributeId() ?>','<?php echo $value['id'] ?>', '<?php echo $_attribute->getPosition() ?>', '<?php echo $_attribute->getProductAttribute()->getAttributeCode() ?>');">
                                                <img src="<?php echo $imageOption['image'] ?>" alt="<?php echo $value['label'] ?>"/>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <div style="display: none" class="validation-advice" data-pass="0"
                                 data-validate="attribute<?php echo $_attribute->getAttributeId() ?>"
                                 id="advice-required-entry-attribute">This is a required field.
                            </div>
                            <?php $y++; ?>
                            <input style="display: none" value="" type="text"
                                   name="product-position-<?php echo $_product->getId() ?>-<?php echo $_attribute->getPosition() ?>"
                                   id="product-position-<?php echo $_product->getId() ?>-<?php echo $_attribute->getPosition() ?>">
                        </dl>
                    <?php endforeach; ?>
                <?php endif ?>

                <h2 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <div class="desc">
                  <?php $_shortDescriptionStripped = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
									<?php
                    if(iconv_strlen($_shortDescriptionStripped,'UTF-8')>30) {
                      $_shortDescriptionStripped = iconv_substr($_shortDescriptionStripped, 0,30, 'UTF-8');
                      $_shortDescriptionStripped .= '...';
                    }
                    ?>
                  <?php echo $_shortDescriptionStripped ?>
                </div>
                <div class="grid-price">
                  <?php echo $this->getPriceHtml($_product, true, $this->getPriceSuffix()) ?>
                  <?php
                    $final_price = $_product->getFinalPrice();
                    $price = $_product->getPrice();
                    $discount_percent = 0;
                    if ($price > 0) $discount_percent = round(($price - $final_price) / $price * 100, 0, PHP_ROUND_HALF_UP);
                  ?>
                  <?php if ($discount_percent) :?>
                    <div class="save-price-percent"><span><?php echo $this->__('Save ') ?><strong><?php echo $discount_percent; ?><?php echo '%' ?></strong></span></div>
                  <?php endif; ?>
                </div>
                
                <div class="actions">
                  <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
										<?php if($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
											<button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<?php else:?>
											<p class="action availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
										<?php endif?>
									<?php else: ?>
											<button type="button" title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button btn-view-details" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><span><span><?php echo $this->__('View Details') ?></span></span></button>
									<?php endif; ?>	
                </div>
            </div>
        <?php endforeach ?>
				</div>
        <div class="clearer"></div>
        <?php if ($this->getPageUrl() && (string)$this->getPageTitle()) : ?>
					<div class="page-link">
						<a href="<?php echo $this->getPageUrl() ?>"><?php echo $this->__((string)$this->getPageTitle()) ?></a>
					</div>
        <?php endif ?>
    </div>
</div>
<script type="text/javascript">
  var widthWindow = jQuery( window ).width();
  if(widthWindow >768){
    jQuery("#bestseller-product-list").owlCarousel({	
      loop:false,
      nav:true,
      responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
      }
    });
  }else{
    jQuery('.categoryproducts .block-content').mCustomScrollbar({
      axis:"x",
      advanced:{autoExpandHorizontalScroll:true}
    }); 
  }
</script>
<script type="text/javascript">

    var jQ = jQuery.noConflict();

    function customgroupCheckAttributeBestSell(itemId, attributeId, value, positionAttribute, label) {
        var inputbox = $('bestsell-customgroup-item-' + itemId + '-attribute' + attributeId);
        var divValidate = inputbox.next();
        var radiocheck = $('bestsell-customgroup-item-' + itemId + '-attribute' + attributeId + '-' + value);
        var attributelinks = inputbox.select('a');
        for (var i = 0; i < attributelinks.length; i++) {
            var attributelink = attributelinks[i];
            if (attributelink.hasClassName('customgroup-attribute-option-link-check'))
                attributelink.removeClassName('customgroup-attribute-option-link-check');
        }
        var attribute_link_check = $('link-bestsell-customgroup-item-' + itemId + '-attribute' + attributeId + '-' + value);
        attribute_link_check.addClassName('customgroup-attribute-option-link-check');
        radiocheck.checked = true;
        $('product-position-' + itemId + '-' + positionAttribute).value = label + '-' + value;
        var attributeSelected = null;
        if (positionAttribute > 0) {
            var positionattributeSelected = positionAttribute - 1;
            attributeSelected = $('product-position-' + itemId + '-' + positionattributeSelected).value;
        }
        //update other action
        var url = '<?php echo $this->getUrl("highlight/index/getOptionBestSellAvailable") ?>';
        var request = new Ajax.Request(url, {
            method: 'get',
            parameters: {
                productId: itemId,
                attributeId: attributeId,
                value: value,
                positionAttribute: positionAttribute,
                label: label,
                attributeSelected: attributeSelected
            },
            onSuccess: function (transport) {
                if (transport.responseJSON.success == 'true') {
                    var key;
                    for (key in transport.responseJSON.resultUpdate) {
                        $(transport.responseJSON.resultUpdate[key]).removeClassName('option_disabled');
                        $(transport.responseJSON.resultUpdate[key]).removeClassName('customgroup-attribute-option-link-check');
                    }

                    var keyRemove;
                    for (keyRemove in transport.responseJSON.resultRemove) {
                        $(transport.responseJSON.resultRemove[keyRemove]).addClassName('option_disabled');
                        $(transport.responseJSON.resultRemove[keyRemove]).removeClassName('customgroup-attribute-option-link-check');
                    }
                }
            }
        });
        divValidate.setAttribute('data-pass', 1);
    }
</script>
