<?php
    $_productCollection = $this->getLoadedProductCollection();
    $_helper            = $this->helper('catalog/output');
    $_collectionSize    = $_productCollection->count();
    $_columnCount       = $this->getColumnCount();
?>
<?php if (!$_collectionSize) : return; endif; ?>
<?php 
	if ($this->getCategoryFilter()) {
		$categoryFilterId = $this->getCategoryFilter();	
		$_category  = Mage::getModel('catalog/category')->load($categoryFilterId);	
		$_categoryUrl = $_category->getUrl().'/?page=productlist';
	}else{
		$_categoryUrl = '#';
	}
?>
<h2 class="title-style1"><span><?php echo $this->__($this->getTitle()) ?></span><a title="<?php echo $this->__('view all')?>" href="<?php echo $_categoryUrl; ?>"><?php echo $this->__('view all')?></a></h2>
<div class="category-products block-highlight <?php echo $this->getClassName() ?>">
    <div class="block-content">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid products-grid--max-<?php echo $_columnCount?>-col">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="prolabel-wrapper">
                  <?php echo Mage::helper('amlabel')->getLabels($_product, 'category'); ?>
                    <a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"
                    ><img class="lazy" src="<?php echo
                        $this->getSkinUrl('images/mgt_lazy_image_loader/loader.gif'); ?>"
                        data-src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>"
                        srcset="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?> 1x, <?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135 * 2); ?> 2x"
                        width="135" height="135"
                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                    /></a>

                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li class="wishlist-ajax-gird add-wishlist">
                                <a id="wishlist-<?php echo $_product->getId()?>" href="<?php if(Mage::helper('customwishlist')->checkItemInWishlist($_product->getId())):?><?php else:?><?php echo $this->helper('wishlist')->getAddUrl($_product) ?><?php endif ?>" data-remodal-target="<?php if(Mage::helper('customwishlist')->checkItemInWishlist($_product->getId())== false):?><?php endif ?>"
                                   class="link-wishlist <?php if(Mage::helper('customwishlist')->checkItemInWishlist($_product->getId())):?>added-item<?php endif ?>"><?php echo $this->__('Add to Wishlist') ?></a><?php ?>
                                <span class="detect-proId" style="display: none"><?php echo $_product->getId();?></span>
                                <div id='ajax_loader' style="display: none">
                                    <img src='<?php echo $this->getSkinUrl('images/review/loader.gif')?>'/>
                                </div>
                            </li>
                        <?php endif;?>
                    </ul>


                </div>

                <h2 class="product-name"><a href="<?php echo $this->getProductUrl($_product) ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <div class="desc">
                    <?php echo $_helper->productAttribute($_product, $_product->getSku(), 'sku') ?>
                </div>
                <div class="grid-price">
                  <?php echo $this->getPriceHtml($_product, true, $this->getPriceSuffix()) ?>
                  <?php
                    $final_price = $_product->getFinalPrice();
                    $price = $_product->getPrice();
                    $discount_percent = 0;
                    if ($price > 0) $discount_percent = round(($price - $final_price) / $price * 100, 0, PHP_ROUND_HALF_UP);
                  ?>
                  <?php if ($discount_percent) :?>
                    <div class="save-price-percent"><span><?php echo $this->__('Save ') ?><strong><?php echo $discount_percent; ?><?php echo '%' ?></strong></span></div>
                  <?php endif; ?>
                </div>
                
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <div class="clearer"></div>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last']);</script>
        <?php if ($this->getPageUrl() && (string)$this->getPageTitle()) : ?>
            <div class="page-link">
                <a href="<?php echo $this->getPageUrl() ?>"><?php echo $this->__((string)$this->getPageTitle()) ?></a>
            </div>
        <?php endif ?>
    </div>
</div>
<script type="text/javascript">
    $j(".wishlist-ajax-gird").click(function(){
        var proId = $j(this).find('.link-wishlist').attr('id');

        <?php if(!$this->helper('customer')->isLoggedIn()):?>
        window.location.href = "<?php echo Mage::getUrl('customer/account/login')?>";
        <?php endif; ?>
        <?php if($this->helper('customer')->isLoggedIn()):?>
        url = '<?php echo $this->getUrl('customwishlist/index/add'); ?>';
        url += 'product/'+$j(this).find('.detect-proId').text();
        id = $j(this).find('.detect-proId').text();
        $j("#ajax_loader").show();
        $j.ajax({
            url: url,
            type: "GET",
            dataType: 'json',
            success: function (data) {
                $j('.box-list-products').find('a#'+proId).attr('href','');
                $j('.box-list-products').find('a#'+proId).addClass('added-item');
                $j("#ajax_loader").hide();
                $j('.col-main').prepend('<ul class="messages"><li class="success-msg"><ul><li><span>'+ data.message + '</span></li></ul></li></ul>');
            }
        });
        <?php endif;?>
    });

</script>