<div class="flipbook-list">
  <div class="page-title style2">
    <h1><?php echo $this->__('INDEX LIVING MALL CATALOG') ?></h1>
  </div>

  <div class="lastest-book">
    <?php $lastest_book = $this->getLastestBook(); ?>
    <div class="box-image">
      <img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'flippingbook/images/thumbnail/'.$lastest_book->getData('magazine_thumbnail');?>" />
    </div>
    <div class="infor-book">
      <div class="date-time">
        <?php
        $createDate = new DateTime($lastest_book->getData('created_at'));
        echo $createDate->format('Y-m-d');
        ?>
      </div>
      <div class="name-book">
        <?php echo $lastest_book->getData('magazine_title') ?>
      </div>
      <div class="short-des"><?php echo $lastest_book->getDescription() ?></div>
      <?php if($lastest_book->getData('magazine_background_pdf') && $lastest_book->getData('magazine_enable_pdf')) : ?>
        <div class="file-size">
          <?php echo $this->__('File Size : ') ?>
          <?php
          $path = Mage::getBaseDir('media').'/flippingbook/pdf/'.$lastest_book->getData('magazine_background_pdf');
          echo $this->formatSizeUnits(filesize($path));
          ?>
          <?php  ?>
        </div>
        <div class="tb_social" style="float: right; margin-left: 0px;">

            <a class="view" title="<?php echo $this->__('View')?>" href="<?php echo $this->getMagazineUrl($lastest_book); ?>"><?php echo $this->__('View') ?></a>

          <?php if ($lastest_book->getMagazineEnablePdf() && $lastest_book->getMagazineBackgroundPdf()): ?>
            <i class="tbicon icon-pdf" title="<?php echo $this->__('Download PDF'); ?>"
               onclick="location.href='<?php echo $this->getPdfUrl($lastest_book); ?>'"><?php echo $this->__('Download') ?></i>
          <?php endif; ?>
<!--          --><?php //if ($lastest_book->getDisplayTopIcons()): ?>
            <div class="box-share">
              <label><?php echo $this->__('Share') ?></label>
              <div class="share-socials">
                <i class="tbicon share-facebook" name="<?php echo $lastest_book->getName(); ?>"  url="<?php echo $this->getMagazineUrl($lastest_book); ?>" title="<?php echo $this->__('Share on facebook'); ?>"></i>
                <i class="tbicon share-twitter" name="<?php echo $lastest_book->getName(); ?>"  url="<?php echo $this->getMagazineUrl($lastest_book); ?>" title="<?php echo $this->__('Share on Twitter'); ?>"></i>
                <i class="tbicon share-plus" name="<?php echo $lastest_book->getName(); ?>"  url="<?php echo $this->getMagazineUrl($lastest_book); ?>" title="<?php echo $this->__('Share on G+'); ?>"></i>
              </div>
            </div>
<!--          --><?php //endif; ?>
        </div>
      <?php endif; ?>
    </div>
  </div>
  <div class="category_book">
    <ul class="categpry_list">
      <li>
        <a href="javascript:;" onclick="getListBooks('all')"title="all"><?php echo $this->__('ALl')?></a>
      </li>
      <?php $category_list= Mage::getModel('flippingbook/category')->getCollection(); ?>
      <?php if($category_list->getData()): ?>
        <?php foreach($category_list as $_category): ?>
          <li>
            <a href="javascript:;" onclick="getListBooks('<?php echo $_category->getId()?>')" title="<?php $_category->getName()?>"><?php echo $_category->getName()?></a>
          </li>
        <?php endforeach; ?>
      <?php endif; ?>
    </ul>
    <ul class="category_book_list" id="category_book_list">
      <div id="all_list">
      <?php $collection = Mage::getModel('flippingbook/magazine')->getCollection(); ?>
      <?php if($collection->getData()): ?>
        <?php foreach($collection as $_magazine): ?>
          <li class="item">
            <div class="box-image">
              <img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'flippingbook/images/thumbnail/'.$_magazine->getData('magazine_thumbnail');?>" />
            </div>
            <div class="infor-book">
              <div class="date-time">
                <?php
                $createDate = new DateTime($_magazine->getData('created_at'));
                echo $createDate->format('Y-m-d');
                ?>
              </div>
              <div class="name-book">
                <?php echo $_magazine->getData('magazine_title') ?>
              </div>
              <div class="file-size">
                <?php echo $this->__('File Size : ') ?>
                <?php
                $path_file = Mage::getBaseDir('media').'/flippingbook/pdf/'.$_magazine->getData('magazine_background_pdf');
                echo $this->formatSizeUnits(filesize($path_file));
                ?>
                <?php  ?>
              </div>
              <div class="tb_social">
                <a class="view" title="<?php echo $this->__('View')?>" href="<?php echo $this->getMagazineUrl($_magazine); ?>"><?php echo $this->__('View') ?></a>
                <?php if ($_magazine->getMagazineEnablePdf() && $_magazine->getMagazineBackgroundPdf()): ?>
                  <i class="tbicon icon-pdf" title="<?php echo $this->__('Download PDF'); ?>"
                     onclick="location.href='<?php echo $this->getPdfUrl($_magazine); ?>'"><?php echo $this->__('Download') ?></i>
                <?php endif; ?>
                <div class="box-share">
                  <label><?php echo $this->__('Share') ?></label>
                  <div class="share-socials">
                    <i class="tbicon share-facebook" name="<?php echo $_magazine->getName(); ?>" url="<?php echo $this->getMagazineUrl($_magazine); ?>" url="" title="<?php echo $this->__('Share on facebook'); ?>"></i>
                    <i class="tbicon share-twitter" name="<?php echo $_magazine->getName(); ?>" url="<?php echo $this->getMagazineUrl($_magazine); ?>" title="<?php echo $this->__('Share on Twitter'); ?>"></i>
                    <i class="tbicon share-plus" name="<?php echo $_magazine->getName(); ?>" url="<?php echo $this->getMagazineUrl($_magazine); ?>" title="<?php echo $this->__('Share on G+'); ?>"></i>
                  </div>
                </div>
              </div>
            </div>
          </li>
        <?php endforeach; ?>
      <?php endif; ?>
      </div>
    </ul>
  </div>
</div>
<script type="text/javascript">
  jQuery('.box-share > label').click(function() {
    if (!jQuery(this).hasClass('active')){
      jQuery(this).next().slideDown();
      jQuery(this).addClass('active');
    }else if (jQuery(this).hasClass('active')) {
      jQuery(this).next().slideUp();
      jQuery(this).removeClass('active');
    }
  });
  jQuery(document).ready(function () {
    clickElement(jQuery(".tbicon"), function (a) {
      var rawPublicationLink =  jQuery(this).attr("url");
      var rawPublicationTitle =  jQuery(this).attr("name");
      navigation(jQuery.trim(jQuery(this).attr("class").replace(/\b([a-z-]*hover|tbicon)\b/g, "")), rawPublicationLink, rawPublicationTitle)
    });
  });
  function clickElement(a, b) {
    jQuery.isTouch ? a.bind(jQuery.mouseEvents.up, b) : a.click(b)
  }
  function navigation(a, rawPublicationLink, rawPublicationTitle) {
    switch (a) {
      case "share-facebook":
        window.open("https://www.facebook.com/sharer.php?u=" + encodeURIComponent(rawPublicationLink) + "&t=" + encodeURIComponent(rawPublicationTitle));
        break;
      case "share-twitter":
        window.open("https://twitter.com/intent/tweet?original_referer=" + encodeURIComponent(rawPublicationLink) + "&url=" + encodeURIComponent(rawPublicationLink) + "&text=" + encodeURIComponent(rawPublicationTitle));
        break;
      case "share-plus":
        window.open("https://plusone.google.com/_/+1/confirm?url=" + encodeURIComponent(rawPublicationLink))
    }
  }

  function getListBooks(id){
    var url = '<?php echo $this->getUrl('flippingbook/index/getListBooksByCategory')?>';
    new Ajax.Request(url, {
      parameters: {
        category_id: id
      },

      onCreate: function() {
        ajaxCart.ajaxLoading.show();
      }.bind(this),

      onComplete: function(response) {
        /* hide ajax loading */
        ajaxCart.ajaxLoading.hide();
        /* show message, update cart info */
          if (response.responseJSON) {
            var html = response.responseJSON.html;
           $('all_list').replace(html);
          }
      }.bind(this)
    });
  }
</script>