<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Scheckout
 */
?>
<?php echo $this->getParentBlock()->getChildHtml("review_before") ?>
<div class="order-review" id="checkout-review-load"><div class="amloading" id="amloading-checkout-review-load"><span class="amscheckout-processing-small">&nbsp;</span></div><div style="display: none;">:AM_REPLACE</div></div>

<?php if (Mage::helper("amscheckout")->showNewsletter() && !$this->isCustomerLoggedIn()) {?>
<div class="order-review-newsletter">
    <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" class="checkbox">
    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
</div>
<?php }?>
<?php
$shippingType = Mage::helper('customaddress')->checkShippingType();
$shippingType = implode(",",$shippingType);
// 114: ILM, 115: THAIPOST
$_product = Mage::getModel('catalog/product');
$attr = $_product->getResource()->getAttribute("am_shipping_type");
$ilm = null;
$thaipost = null;
if ($attr->usesSource()) {
    $ilm = $attr->getSource()->getOptionId("ILM");
    $thaipost = $attr->getSource()->getOptionId("Thaipost");
}
$hasILM = strpos($shippingType, $ilm);
$hasTHAIPOST = strpos($shippingType, $thaipost);
?>
<div class="order-review-button">
	<div id='comment'>

	</div>
    <button <?php if($hasILM || $hasTHAIPOST): ?> disabled <?php endif; ?> id="amscheckout-submit" type="button" title="<?php echo $this->__('Place Order') ?>" class="button" onclick="completeCheckout();">
        <span><span><?php echo $this->__('Place Order') ?></span></span>
    </button>
</div>
<div class="clearboth" style="clear: both"></div>
<p id="notice_service" style="display: none; color: red;"><?php echo $this->__('Remark : Shipping and installing prices are not included an island ferry boat. Ferry price will be charge on delivery as real price. (More info please call 02-417-1111)')?></p>