<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_SeoReviews
 */
?>
<?php if ($this->getReviewsCount()): ?>
	<div class="review-box page-container">
		<div class="box-title">
			<div class="bl">
				<h2><?php echo $this->__('Customer Reviews')?></h2>	
				<div>
				<p class="rating-overall"><?php echo $this->__('Overall Product Rating')?></p>
				<div class="ratings ratings-overview">
					<?php $helper = Mage::helper('amseoreviews');
					if($helper->isRedirectToProductPageEnabled()){ ?>
							<script> window.addEventListener("load", hrefChecker, false);
							function hrefChecker(){
									$$("#customer-reviews dt a").each(function(val) {
											var label = "<strong><u>" + val.innerHTML + "</u></strong>";
											val.replace(label);
									});
							}</script>
					<?php } ?>

					<?php if($this->getRatingSummary()):
							echo $this->getCssJsHtml(); ?>
							<div class="rating-box">
									<div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
							</div>
							<?php $ratingSummary = $this->getRatingSummary();?>
							<?php $ratingAverage = ($ratingSummary * 5)/100;?>
							<h3 class="rating-average"><?php echo $this->__('%.1f / 5', $ratingAverage)?></h3>
							<div class="rating-summary">	
								<div class="rating-box-big">
										<div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
								</div>
							</div>
					<?php endif; ?>
				</div>
				<div class="rating-summary-details">
					<?php echo $this->getLayout()->createBlock('rating/entity_detailed')->setEntityId($this->getProduct()->getId())->toHtml() ?>
				</div>
				</div>
			</div>
			<div class="br">
				<h3 class="review-count"><?php echo $this->__('%d Reviews', $this->getReviewsCount()) ?></h3>
				<p><?php echo $this->__('Own this product? Let us know what you think and write a review.')?></p>
				<p class="rating-links">
					<a class="write-review-popup" href="#review-form-popup" title=""><?php echo $this->__('Write a review')?></a>
				</p>
			</div>
		</div>
	</div>
<?php elseif($this->getDisplayIfEmpty()): ?>
	<div class="review-box page-container">
		<div class="box-title">
			<div class="bl">
				<h2><?php echo $this->__('Customer Reviews')?></h2>	
				<div>
					<p class="rating-overall"><?php echo $this->__('Overall Product Rating')?></p>
					<div class="ratings ratings-overview">
						<div class="rating-box">
							<div class="rating" style="width:0%"></div>
						</div>
						<h3 class="rating-average"><?php echo $this->__('0 / 0')?></h3>
						<div class="rating-summary">	
							<div class="rating-box-big">
									<div class="rating" style="width:0%"></div>
							</div>
						</div>
					</div>
					<div class="rating-summary-details">
						<?php echo $this->getLayout()->createBlock('rating/entity_detailed')->setEntityId($this->getProduct()->getId())->toHtml() ?>
					</div>
				</div>
			</div>	
			<div class="br">
				<h3 class="review-count"><?php echo $this->__('0 Reviews') ?></h3>
				<p><?php echo $this->__('Own this product? Let us know what you think and write a review.')?></p>
				<p class="rating-links">
					<a class="write-review-popup" href="#review-form-popup" title=""><?php echo $this->__('Write a review')?></a>
				</p>
			</div>
		</div>	
	</div>	
<?php endif; ?>
<script type="text/javascript">
	jQuery(document).ready(function() {
		jQuery('.write-review-popup').fancybox({
			afterShow:function(){
				jQuery('#review-form-popup').customRadioCheckbox();
			}
		});
	});
</script>
