<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Model_Mysql4_Category_Collection $collection  */
/** @var Magpleasure_Blog_Block_Sidebar_Category $this  */
$collection = $this->getCollectionByLanding('category_is_landing_project');
//$category = Mage::getBlockSingleton('mpblog/content_category')->getCategory();
?>
<?php if ($this->getDisplay() && count($collection)): ?>
  <div class="block mpblog-categories">
    <div class="block-content">
      <label class="show-mplog-categories box-mobile">
        <span class="title-show"><?php echo $this->__('Show Navigation') ?></span>
        <span class="title-hide"><?php echo $this->__('Hide Navigation') ?></span>
      </label>
      <ul class="mplog-categories box-desktop">
        <?php foreach ($collection as $category): ?>
          <?php
          $subcate_ids_2 = $category->getData('sub_category');
          if($subcate_ids_2):
            $subcate_ids_2 = explode(',', $subcate_ids_2);
            ?>
            <?php
            foreach($subcate_ids_2 as $subcate_id_2):
              $collection_subcate_2 = $this->getCollectionSubcate($subcate_id_2);
              ?>
              <?php if ($collection_subcate_2['status'] == 1): ?>
              <li class="mpblog-category level-2">
                <a href="<?php echo $collection_subcate_2->getCategoryUrlSubcate(null,$subcate_id_2); ?>" class="categories-title"><?php echo $this->escapeHtml($collection_subcate_2['name']); ?></a>
                <?php
                $subcate_ids_3 = $collection_subcate_2->getData('sub_category');
                if($subcate_ids_3):
                  $subcate_ids_3 = explode(',', $subcate_ids_3);
                  ?>
                  <ul class="mplog-sub-categories-level-3">
                    <?php
                    foreach($subcate_ids_3 as $subcate_id_3):
                      $collection_subcate_3 = $this->getCollectionSubcate($subcate_id_3);
                      ?>
                      <?php if ($collection_subcate_3['status'] == 1): ?>
                      <li class="mpblog-category" id="level-2">
                        <a href="<?php echo $collection_subcate_3->getCategoryUrlSubcate(null,$subcate_id_3); ?>"><?php echo $this->escapeHtml($collection_subcate_3['name']); ?></a>
                      </li>
                    <?php endif ?>
                    <?php endforeach; ?>
                  </ul>
                <?php endif ?>
              </li>
            <?php endif ?>
            <?php endforeach; ?>
          <?php endif ?>
        <?php endforeach; ?>
      </ul>
      <script type="text/javascript">
        jQuery(document).ready(function(){
          jQuery(".show-mplog-categories").click(function() {
            if (!jQuery(this).hasClass('active')){
              jQuery(this).next().slideDown();
              jQuery(this).addClass('active');
            }else if (jQuery(this).hasClass('active')) {
              jQuery(this).next().slideUp();
              jQuery(this).removeClass('active');
            }
          });
        });
      </script>
    </div>
  </div>
<?php endif; ?>

