<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Block_Sidebar_Recentpost $this */

/** @var Magpleasure_Blog_Model_Mysql4_Category_Collection $collection  */
$collection = $this->getCollection();
?>
<?php if ($this->getDisplay() && count($collection)): ?>
<div class="block mpblog-recentposts mpblog-recentposts-style2">
    <div class="block-title title-style6">
        <strong><span><?php echo $this->__('Other Promotion'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="mpblog-list-style2">
        <?php $i=0; foreach ($collection as $post): $i++;?>
            <?php /** @var Magpleasure_Blog_Model_Post $post */ ?>
            <?php if($i > 4) break; ?>
            <li class="mpblog-post">
                <div class="post-image">
                    <?php if ($post->getListThumbnailSrc()): ?>
                        <div class="thumbnail-container">
                            <div class="post-thumbnail">
                                <a
                                  href="<?php echo $post->getPostUrl(); ?>"
                                  title="<?php echo $this->escapeHtml($post->getTitle()); ?>">

                                    <img class="thumbnail"
                                         src="<?php echo $post->getListThumbnailSrc(); ?>"
                                         alt="<?php echo $this->escapeHtml($post->getTitle()); ?>"/>
                                </a>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="post-info">
                    <div class="mp-post-title">
                        <a href="<?php echo $post->getPostUrl(); ?>"><?php echo $this->escapeHtml($post->getTitle()); ?></a>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
