<?php
$values = $this->getValuesData();

$application_for_job_id = $values['application_for_job_id'];
$ageId = $values['work_age'];
$age = Mage::helper('career')->getTitleAge($ageId);
$work_type_id = $values['work_type'];

$jobTitle = Mage::getModel('career/job')->load($application_for_job_id)->getData('title');
$work_type_title = null;
if($work_type_id){
  $workTypeCollection = Mage::getModel('career/worktype')->load($work_type_id);
  $work_type_title = $workTypeCollection->getData('title');
}
?>
<style type="text/css">
  .application_form{
    width: 100%;
    font-size: 13px;
    padding: 10px;
    border: 1px solid #cbd3d4;
  }
  .application_form tbody td{
    border-width: 0 1px 1px 0;
    border-color: #dadfe0;
    border-style: solid;
    padding: 3px;
  }
  .application_form thead th{
    border-bottom-width: 1px;
    border-bottom-color: #dadfe0;
    border-bottom-style: solid;
    padding-top: 1px;
  }
  td#lable {
    width: 55%;
  }
</style>
<div class="content-header">
  <table cellspacing="0" >
    <tr>
      <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('catalog')->__('Application Form') ?></h3></td>
      <td class="a-right">
        <?php echo $this->getButtonsHtml() ?>
      </td>
    </tr>
  </table>
</div>
<table class="application_form" onscroll="">
  <thead>
  <tr>
    <th>
      <span><?php echo $this->__('Questions')?></span>
    </th>
    <th>
      <span><?php echo $this->__('Answers')?></span>
    </th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td id="lable"><label for="identity_number"><?php echo $this->__('Identity Number')?></label></td>
    <td><?php echo $values['identity_number']?></td>
  </tr>
  <tr>
    <td id="lable"><label for="application_for_job_id"><?php echo $this->__('Application For Job')?></label></td>
    <td><?php echo $jobTitle ?></td>
  </tr>
  <tr>
    <td id="lable"><label for="email"><?php echo $this->__('Email')?></label></td>
    <td><?php echo $values['email']?></td>
  </tr>
  <tr>
    <td id="lable"><label for="name"><?php echo $this->__('Name')?></label></td>
    <td><?php echo $values['name']?></td>
  </tr>
  <tr>
    <td id="lable"><label for="surname"><?php echo $this->__('Surname')?></label></td>
    <td><?php echo $values['surname']?></td>
  </tr>
  <tr>
    <td id="lable"><label for="tel"><?php echo $this->__('Telephone')?></label></td>
    <td><?php echo $values['tel']?></td>
  </tr>
  <tr>
    <td id="lable"><label for="date_of_birth"><?php echo $this->__('Date Of Birth')?></label></td>
    <td><?php echo $values['date_of_birth']?></td>
  </tr>
  <tr>
    <td id="lable"><label for="work_type"><?php echo $this->__('Work Type')?></label></td>
    <td><?php echo $work_type_title?></td>
  </tr>
  <tr>
    <td id="lable"><label for="work_age"><?php echo $this->__('Work Age')?></label></td>
    <td><?php echo $age?></td>
  </tr>
  <tr>
    <td id="lable"><label for="present_company"><?php echo $this->__('Present Company')?></label></td>
    <td><?php echo $values['present_company']?></td>
  </tr>
  <tr>
    <td id="lable"><label for="last_position"><?php echo $this->__('Last Position')?></label></td>
    <td><?php echo $values['last_position']?></td>
  </tr>
  <tr>
    <td id="lable"><label for="created_at"><?php echo $this->__('Join date')?></label></td>
    <td><?php echo $values['created_at']?></td>
  </tr>
  <?php $pathMedia = Mage::getBaseUrl('media') . 'career/'; ?>
  <?php $_extensImage = array('jpg', 'png', 'gif'); ?>
  <tr>
    <td id="lable"><label for="attachment"><?php echo $this->__('Attachment')?></label></td>
  <?php foreach ($values as $key => $value) {
    ?>

      <?php if ($value && $key != 'status') :?>
        <?php if ($key == 'attachment') : ?>
          <td>
            <?php $extensions = explode('.', $value); ?>
            <?php if (in_array($extensions[count($extensions) - 1], $_extensImage)): ?>
              <a download="<?php echo $value ?>" href="<?php echo $pathMedia . $value ?>"><img src="<?php echo $pathMedia . $value ?>" width="100px" ></a>
            <?php else : ?>
              <a href="<?php echo $pathMedia . $value ?>" target="_blank"><?php echo $value ?></a>
            <?php endif; ?>
          </td>
        <?php endif; ?>
      <?php endif; ?>
  <?php } ?>
  </tr>
  </tbody>
</table>
