<?php
/**
 * @author      Sashas
 * @category    Sashas
 * @package     Sashas_NotificationBar
 * @copyright   Copyright (c) 2014 Sashas IT Support Inc. (http://www.sashas.org)
 * @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
 */
?>
<?php if ($this->ShowBar()):?>
<style>
<!--
/*.sashas-notificationbar {
    width:100%;
    position: <?php echo $this->getPosition();?>;
    z-index: 100;
    top: 0;
    left: 0;
    right: 0;
    background: <?php echo $this->getColor();?>;
    text-align: center;
    line-height: 2.5;
    overflow: hidden;
    -webkit-box-shadow: 0 0 5px black;
    -moz-box-shadow:    0 0 5px black;
    box-shadow:         0 0 5px black;
    opacity:<?php echo $this->getOpacity();?>;
}
.sashas-notificationbar #close {
    cursor:pointer;
    padding-left:2px;
} */
.sashas-notificationbar img{
    -webkit-box-shadow: 0 0 5px black;
    -moz-box-shadow: 0 0 5px black;
    box-shadow: 0 0 5px black;
    opacity: 5;
}
a#close {
    background: #252525;
    color: #FFF;
    border-radius: 20px;
    width: 30px;
    height: 30px;
    float: right;
    font-size: 17px;
    font-weight: bold;
    line-height: 28px;
    position: relative;
    top: 24px;
    right: -10px;
}
a#close:hover{text-decoration: none;background: #FFC222;}
<?php echo $this->getCss();?>
-->
</style>
<div id="notification-bar" class="sashas-notificationbar"><sup><a id="close" href="javascript:void(0);" onclick="hidebar();">X</a></sup><?php //echo $this->__($this->getBarText())?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('notification-popup')->toHtml();?>
</div>
<script  type="text/javascript" language="javascript">
function hidebar() {
     $('notification-bar').hide();
     <?php if ($this->useSession()): ?>
     new Ajax.Request('<?php echo Mage::getUrl('notificationbar/notificationbar/closebar');?>', {
          method: 'get'
          });
     <?php endif;?>
}
</script>

<?php endif;?>