<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" autocomplete="off" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
  <div class="fieldset">
    <h2><?php echo $this->__('Application Form') ?></h2>
    <ul class="form-list">
      <li class="fields">
        <div class="field">
          <label for="contact_person_name" class="required"><em>*</em><?php echo $this->__('Contact Person Name') ?></label>
          <div class="input-box">
            <input type="text"  name="contact_person_name" id="contact_person_name" value="" title="<?php echo $this->__('Contact Person Name') ?>" class="input-text" />
          </div>
        </div>
        <div class="field">
          <label for="company_name" class="required"><em>*</em><?php echo $this->__('Company Name') ?></label>
          <div class="input-box">
            <input type="text" name="company_name" id="company_name"  value="" title="<?php echo $this->__('Company Name') ?>" class="input-text" />
          </div>
        </div>
      </li>
      <li class="fields">
        <div class="field">
          <label for="address " class="required"><em>*</em><?php echo $this->__('Address ') ?></label>
          <div class="input-box">
            <input type="text" name="address" id="address"  value="" title="<?php echo $this->__('Address ') ?>" class="input-text" />
          </div>
        </div>
        <div class="field">
          <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
          <div class="input-box">
            <input type="text" name="country" id="country" value="" title="<?php echo $this->__('Country') ?>" class="input-text" />
          </div>
        </div>
      </li>
      <li class="fields">
        <div class="field">
          <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
          <div class="input-box">
            <input type="text" name="telephone" id="telephone" value="" title="<?php echo $this->__('Telephone') ?>" class="input-text" />
          </div>
        </div>
        <div class="field">
          <label for="fax" class="required"><em>*</em><?php echo $this->__('Fax') ?></label>
          <div class="input-box">
            <input type="text" name="fax" id="fax" value="" title="<?php echo $this->__('Fax') ?>" class="input-text" />
          </div>
        </div>
      </li>
      <li class="fields">
        <div class="field">
          <label for="website " class="required"><em>*</em><?php echo $this->__('Website ') ?></label>
          <div class="input-box">
            <input type="text" name="website" id="website" value="" title="<?php echo $this->__('Website ') ?>" class="input-text" />
          </div>
        </div>
        <div class="field">
          <label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
          <div class="input-box">
            <input type="text" name="email" id="email" value="" title="<?php echo $this->__('Email') ?>" class="input-text" />
          </div>
        </div>
      </li>
    </ul>
    <div class="buttons-set">
      <div class="note-required"><?php echo $this->__('* You must fill in the information.') ?></div>
      <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
    </div>
  </div>
</form>