<?php if (count($this->getCollection())): ?>

  <div class="mpblog-list list">

    <?php $i=0; foreach ($this->getCollection() as $post): $i++;?>
      <?php /** @var Magpleasure_Blog_Model_Post $post */ ?>
      <div class="mpblog-post" onclick="showImages(<?php echo $post->getId() ?>)">
        <div class="post-image" id="post-image-<?php echo $post->getId() ?>">
          <?php if( $i == 1):   ?>
            <?php if ($post->getPostThumbnailSrc()): ?>
              <div class="post-thumbnail">
                <img class="thumbnail"
                     src="<?php echo $post->getPostThumbnailSrc(); ?>"
                     alt="<?php echo $this->escapeHtml($post->getTitle()); ?>"/>
              </div>
            <?php endif; ?>
          <?php else:?>
            <?php if ($post->getListThumbnailSrc()): ?>
              <div class="thumbnail-container">
                <div class="post-thumbnail">
                  <img class="thumbnail"
                       src="<?php echo $post->getListThumbnailSrc(); ?>"
                       alt="<?php echo $this->escapeHtml($post->getTitle()); ?>"/>
                </div>
              </div>
            <?php endif; ?>
          <?php endif;?>
          <?php $category_name = $this->getCategory()->getData('name');?>
          <div class="post-tag"><span><?php echo $this->__(''.$category_name)?></span></div>
          <div class="popup-image">
            <div class="popup-content parent_content_<?php echo $post->getId() ?>" id="parent_content_<?php echo $post->getId() ?>" ></div>
          </div>
          <script type="text/javascript">
            setTimeout(function(){
              jQuery(document).ready(function() {
                jQuery('.main-slider-id<?php echo $post->getId() ?> .voucher-gallery-thumbs').fancybox({
                  prevEffect : 'none',
                  nextEffect : 'none',
                  closeBtn  : true,
                  arrows    : true,
                  nextClick : true,
                  helpers : {
                    thumbs : {
                      width  : 86,
                      height : 86
                    }
                  }
                });
              });
            }, 1000);

          </script>
        </div>
        <div class="post-info">
          <div class="box-left">
            <div class="mp-post-title">
              <?php echo $this->escapeHtml($post->getTitle()); ?>
            </div>
            <div class="mp-content">
              <?php echo $post->getFullContent(); ?>
            </div>
          </div>
          <div class="box-right">
            <img alt="image logo" src="<?php echo $this->getSkinUrl('images/blog/logo1.jpg') ?>" />
          </div>
        </div>
      </div>
    <?php endforeach; ?>
  </div>
<?php else: ?>
  <?php echo $this->__("There are no posts yet."); ?>
<?php endif; ?>
<script type="text/javascript">
//  jQuery(".pagination-mobie #a-previous").click(function(event) {
jQuery(document).on('click', '.pagination-mobie #a-previous', function () {
    var page = jQuery('#a-previous').html();
    page = parseInt(page);
    checkEnableNextPreviousButton(page);
    updatePageMobie(page);
  });
</script>
