<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>
<?php
$home_decor = Magpleasure_Blog_Model_Categorystyle::HOME_DECOR;
$promotions = Magpleasure_Blog_Model_Categorystyle::PROMOTION;
$newevent_crs = Magpleasure_Blog_Model_Categorystyle::NEWEVENT_CSR;
$index_project = Magpleasure_Blog_Model_Categorystyle::INDEX_PROJECT;
?>

<?php  $category  = $this->getCategory();?>
<?php  $show_landing_field  = $category->getData('category_is_landing')?>
<?php $category_style = $category->getData('category_style'); ?>
<?php
if($category_style == $home_decor){
  if($show_landing_field){
    echo $this->getChildHtml('list.decor2');
  }
  else{
    echo $this->getChildHtml('list.decor2');
  }
}elseif($category_style == $promotions){
  echo $this->getChildHtml('list.promotion');
}elseif($category_style == $newevent_crs){
  echo $this->getChildHtml('list.news.event');
}elseif($category_style == $index_project){
  echo $this->getChildHtml('list.project');
}
?>

