<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>

<div class="mpblog-container list list-promotion">
    <div class="mp-blog-head fix-me">
        <h1 class="mp-title title-promotion">
            <?php echo $this->__('Index living mall %s',$this->getPageHeader()) ; ?>
        </h1>
    </div>
    <?php if (count($this->getCollection())): ?>
        <div class="mpblog-list list">
            <?php $i=0; foreach ($this->getCollection() as $post): $i++;?>
                <?php /** @var Magpleasure_Blog_Model_Post $post */ ?>
                <div class="mpblog-post">
                    <div class="post-image">
                        <?php if ($post->getListThumbnailSrc()): ?>
                            <div class="thumbnail-container">
                                <div class="post-thumbnail">
                                    <a
                                      href="<?php echo $post->getPostUrl(); ?>"
                                      title="<?php echo $this->escapeHtml($post->getTitle()); ?>">

                                        <img class="thumbnail"
                                             src="<?php echo $post->getListThumbnailSrc(); ?>"
                                             alt="<?php echo $this->escapeHtml($post->getTitle()); ?>"/>
                                    </a>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="post-info">
                        <div class="mp-header">
                            <?php if ($post->getCreatedAt()): ?>
                                <span class="post-time">
                                    <?php echo date('d F Y', strtotime($post->getCreatedAt()));; ?>
                                </span>
                            <?php endif; ?>
                        </div>
                        <div class="mp-post-title">
                            <a href="<?php echo $post->getPostUrl(); ?>"><?php echo $this->escapeHtml($post->getTitle()); ?></a>
                        </div>
                        <ul class="mp-details fix-me">
                            <li>
                                <a class="mp-view" href="<?php echo $this->getReadMoreUrl($post); ?>" title="<?php echo $this->__("View"); ?>">
                                    <?php echo $this->__("View"); ?>
                                </a>
                            </li>
                            <li>
                                <a class="mp-download" title="<?php echo $this->__("Download"); ?>" href="<?php echo  $path = Mage::getBaseUrl('media').DS . 'magebuzz'. DS . 'doccument'. DS . 'promotion'. DS . $post->getDocumentPromotion()?>">
                                    <?php echo $this->__("Download"); ?>
                                </a>
                            </li>
                            <?php //if ($helper->getSocialEnabled()): ?>
                                <li class="box-shares">
                                    <a class="mp-share link-share" title="<?php echo $this->__("Share"); ?>" href="javascript:void(0)" id="shareProductLink">
                                        <?php echo $this->__("Share"); ?>
                                    </a>
                                    <?php echo $this->getChildHtml('mpblog_social'); ?>
                                </li>

                            <?php //endif; ?>
                        </ul>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $this->getToolbarHtml(); ?>
        <script type="text/javascript" >
            jQuery('.mp-share').click( function(){
                jQuery(this).next().toggle();
            });
        </script>
    <?php else: ?>
        <?php echo $this->__("There are no posts yet."); ?>
    <?php endif; ?>
</div>

