<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>
<?php
$home_decor = 1;
$promotions = 2;
$newevent_crs = 3;
$index_project = 4;
?>

<?php  $category  = $this->getCategory(); ?>
<?php $category_style = $category->getData('category_style'); ?>
<?php
if($category_style == $home_decor){
  echo $this->getChildHtml('list.decor');
  //echo $this->getChildHtml('list.decor2');
}elseif($category_style == $promotions){
  echo $this->getChildHtml('list.promotion');
}elseif($category_style == $newevent_crs){
  echo $this->getChildHtml('list.news.event');
}elseif($category_style == $index_project){
  echo $this->getChildHtml('list.project');
}
?>

