<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */
?>
<div class="mpblog-container list list-decor list-decor-style2">
    <div class="mp-blog-head fix-me">
        <h1 class="mp-title"><?php echo $this->getPageHeader(); ?></h1>
    </div>
    <?php if (count($this->getCollection())): ?>
        <div class="mpblog-list list">
            <?php $i=0; foreach ($this->getCollection() as $post): $i++;?>
                <?php /** @var Magpleasure_Blog_Model_Post $post */ ?>
                <div class="mpblog-post">
                    <div class="post-image">
                        <?php if ($post->getListThumbnailSrc()): ?>
                            <div class="thumbnail-container">
                                <div class="post-thumbnail">
                                    <a
                                      href="<?php echo $post->getPostUrl(); ?>"
                                      title="<?php echo $this->escapeHtml($post->getTitle()); ?>">

                                        <img class="thumbnail"
                                             src="<?php echo $post->getListThumbnailSrc(); ?>"
                                             alt="<?php echo $this->escapeHtml($post->getTitle()); ?>"/>
                                    </a>
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="post-tag"><span><?php echo $this->__('Kitchen')?></span></div>
                    </div>
                    <div class="post-info">
                        <div class="mp-header">
                            <?php if ($post->getCreatedAt()): ?>
                                <span class="post-time">
                                    <?php echo date('d F Y', strtotime($post->getCreatedAt()));; ?>
                                </span>
                            <?php endif; ?>
                            <div class="post-views">
                                <strong><?php echo $post->getViews() ?></strong>
                                <span></span><?php echo $this->__('Views') ?> </span>
                            </div>
                        </div>
                        <div class="mp-post-title">
                            <a href="<?php echo $post->getPostUrl(); ?>"><?php echo $this->escapeHtml($post->getTitle()); ?></a>
                        </div>
                        <div class="mp-content std fix-me">
                            <?php echo $post->getShortContent(); ?>
                        </div>
                        <div class="mp-details fix-me">
                            <a class="mp-read-more" href="<?php echo $this->getReadMoreUrl($post); ?>" title="<?php echo $this->__("Read More"); ?>">
                                <?php echo $this->__("Read More >"); ?>
                            </a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php echo $this->getToolbarHtml(); ?>
    <?php else: ?>
        <?php echo $this->__("There are no posts yet."); ?>
    <?php endif; ?>
</div>