<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Helper_Data $helper  */
$helper = $this->_helper();
/** @var Magpleasure_Blog_Model_Post $post  */
$post = $this->getPost();

/** @var Magpleasure_Blog_Block_Content_Post $this */
?>
<div class="mpblog-2column-right mpblog-post-promotiom">
  <div class="back-pre-url top promo">
    <span id="back-pre-url" onclick="backPre()" style="cursor: pointer; color: #000"><span class="arrow"><?php echo ' < '?></span><?php echo $this->__('BACK')?></span>
  </div>
    <div class="mp-blog-head fix-me">
        <h1 class="mp-title title-promotion">
            <span></span><?php echo $this->escapeHtml($post->getTitle()); ?></span>
            <ul class="mp-details fix-me">
              <li>
                <a class="mp-view active" href="<?php echo $this->getReadMoreUrl($post); ?>" title="<?php echo $this->__("View"); ?>">
                  <?php echo $this->__("View"); ?>
                </a>
              </li>
              <?php if($post->getDocumentPromotion()):?>
              <li>
                <a class="mp-download" title="<?php echo $this->__("Download"); ?>" href="<?php echo  $path = Mage::getBaseUrl('media').DS . 'magebuzz'. DS . 'doccument'. DS . 'promotion'. DS . $post->getDocumentPromotion()?>">
                  <?php echo $this->__("Download"); ?>
                </a>
              </li>
              <?php endif ?>
              <?php //if ($helper->getSocialEnabled()): ?>
              <li class="box-shares">
                <a class="mp-share link-share" title="<?php echo $this->__("Share"); ?>" href="javascript:void(0)" id="shareProductLink">
                  <?php echo $this->__("Share"); ?>
                </a>
                <?php echo $this->getChildHtml('mpblog_social'); ?>
              </li>
              <?php //endif; ?>
            </ul>
        </h1>
    </div>
    <div class="mpblog-col-content">
        <div class="mpblog-container">
            <div class="mpblog-post mpblog-post-view">
                <?php if ($post->getPostThumbnailSrc()): ?>
                    <div class="post-thumbnail">
                        <?php if ($this->hasThumbnailUrl()): ?>
                            <a class="thumbnail-url" title="<?php echo $this->escapeHtml($post->getTitle()); ?>" href="<?php echo $this->getThumbnailUrl(); ?>">
                                <?php endif; ?>
                                <img class="thumbnail"
                                     src="<?php echo $post->getPostThumbnailSrc(); ?>"
                                     alt="<?php echo $this->escapeHtml($post->getTitle()); ?>"/>
                                <?php if ($this->hasThumbnailUrl()): ?>
                            </a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <div class="mp-content std fix-me">
                    <?php echo $post->getFullContent(); ?>
                  <?php
                  $catalogId = $post->getData('catalog');
                  if($catalogId):
                    $book = Mage::getModel('flippingbook/magazine')->load($catalogId);
                    $bookUrl = Mage::getBlockSingleton('flippingbook/frontend_list')->getMagazineUrl($book);
                  ?>
                    <h2><?php echo $this->__('Catalog')?></h2>
                    <div class="catalog-content">
                      <div class="box-image">
                        <a href="<?php echo $bookUrl ?>" title="<?php echo $book->getData('magazine_title') ?>">
                          <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'flippingbook/images/thumbnail/'.$book->getData('magazine_thumbnail');?>">
                        </a>
                      </div>
                      <div class="infor-book">
                        <div class="date-time">
                          <?php
                          $createDate = new DateTime($book->getData('created_at'));
                          echo $createDate->format('j F, Y');
                          ?>
                        </div>
                        <div class="name-book">
                          <?php echo $book->getData('magazine_title') ?>
                        </div>
                      </div>
                    </div>
                  <?php endif ?>
                  <div class="popup-image" style="display: none">
                    <div class="popup-content parent_content_<?php echo $post->getId() ?>" id="parent_content_<?php echo $post->getId() ?>">
                    </div>
                  </div>
                </div>
            </div>
        </div>
<!--      --><?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('related-in-blogpost')->toHtml();?>
      <div class="back-pre-url">
        <span id="back-pre-url" onclick="backPre()" style="cursor: pointer; color: #000"><?php echo ' < '.$this->__('BACK')?></span>
      </div>
    </div>
    <div class="mpblog-col-right">
        <?php echo $this->getChildHtml('recentpost')?>
    </div>
</div>
<script type="text/javascript" >
  jQuery('.mp-share').click( function(){
    jQuery(this).next().toggle();
  });
</script>
<script type="text/javascript">
  setTimeout(function(){
    jQuery(document).ready(function() {
      jQuery('.main-slider-id<?php echo $post->getId() ?> .voucher-gallery-thumbs').fancybox({
        prevEffect : 'none',
        nextEffect : 'none',
        closeBtn  : true,
        arrows    : true,
        loop: false,
        nextClick : true,
        helpers : {
          thumbs : {
            width  : 125,
            height : 86
          }
        }
      });
    });
  }, 1000);

</script>
<script type="text/javascript">
  jQuery(".mpblog-post.mpblog-post-view .mp-content a img").click(function() {
    jQuery.ajax({
      type: "post",
      url: "<?php echo $this->getUrl('mpblog/index/getSlideImagesContentPost'); ?>?postId=" + <?php echo $post->getId() ?>,
      success: function (transport) {
        if (transport.success == 'true') {
          jQuery('.parent_content_'+<?php echo $post->getId() ?>).html(transport.result);
          jQuery(".popup_img_li_"+<?php echo $post->getId() ?>).first().children().click();
        }
      }
    });
  });
</script>
