<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Helper_Data $helper  */
$helper = $this->_helper();
/** @var Magpleasure_Blog_Model_Post $post  */
$post = $this->getPost();

/** @var Magpleasure_Blog_Block_Content_Post $this */
?>
<?php //echo $this->getChildHtml('post.decor'); ?>
<?php //echo $this->getChildHtml('post.promotion'); ?>
<?php echo $this->getChildHtml('post.news.event'); ?>


