<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Magpleasure_Blog
 */

/** @var Magpleasure_Blog_Helper_Data $helper  */
$helper = $this->_helper();
/** @var Magpleasure_Blog_Model_Post $post  */
$post = $this->getPost();

/** @var Magpleasure_Blog_Block_Content_Post $this */
?>
<div class="mpblog-2column-right post-detail-news-event">
    <div class="mpblog-col-right">
        <div class="blog-banners-right">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('index-corp-blog-bannerright')->toHtml() ?>
        </div>
    </div>
    <div class="mpblog-col-content">
        <div class="mpblog-container">
            <div class="mpblog-post mpblog-post-view">
                <div class="back-pre-url top">
                    <span id="back-pre-url" onclick="backPre()" style="cursor: pointer; color: #000"><span class="arrow"><?php echo ' < '?></span><?php echo $this->__('BACK')?></span>
                </div>
                <div class="mp-blog-head fix-me">
                    <h1 class=""><?php echo $this->escapeHtml($post->getTitle()); ?></h1>
                </div>
                <div class="mp-header">
                    <div class="post-views">
                        <strong><?php echo $post->getViews() ?></strong>
                        <span></span><?php echo $this->__('Views') ?> </span>
                    </div>
                    <?php if ($helper->getSocialEnabled()): ?>
                        <?php if ($helper->getSocialEnabled()): ?>
                            <?php echo $this->getSocialHtml(); ?>
                        <?php endif; ?>

                    <?php endif; ?>
                </div>
                <div class="mp-content std fix-me">
                    <?php echo $post->getFullContent(); ?>
                </div>
            </div>
            <?php echo $this->getChildHtml('recentpost')?>
        </div>
      <div class="back-pre-url">
        <span id="back-pre-url" onclick="backPre()" style="cursor: pointer; color: #000"><?php echo ' < '.$this->__('BACK')?></span>
      </div>
        <div class="thumbs" style="display: none">
            <div class="fotorama"
                 data-auto="false"
                 data-allow-full-screen="true"
                 data-thumb-width="70"
                 data-thumb-height="47"
                 data-nav="thumbs">
                <?php echo Mage::helper('mpblog')->getImages($post->getId()) ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(function($) {
        var token = '<?php echo Mage::helper('amajaxlogin/facebook')->getAppId(); ?>|<?php echo Mage::helper('amajaxlogin/facebook')->getSecretId(); ?>';
        $(document).ready(function(){
            $.ajax({
                url: 'https://graph.facebook.com/v2.7/',
                dataType: 'jsonp',
                type: 'GET',
                data: {access_token: token, id: '<?php echo Mage::helper('core/url')->getCurrentUrl() ?>' },
                success: function(data){
                    $('#results').html(data.share.share_count);
                }
            });
            return false;
        })
    });
</script>
<script type="text/javascript">
    jQuery(function($) {

        // overlay for smoother fullscreen enter
        var $overlay = $('<div class="fotorama-overlay"></div>')
          .css({position: 'fixed', top: 0, right: 0, bottom: 0, left: 0, zIndex: 10001})
          .fadeTo(0, 0)
          .hide()
          .appendTo('body');

        // take all .fotorama blocks
        $('.thumbs').each(function () {
            var $thumbs = $(this),

            // clone it and make fotorama
              $fotorama = $('.fotorama', $thumbs)
                .clone()
                  //.show()
                .css({position: 'absolute', left: -99999, top: -99999})
                .appendTo('body')
                .fadeTo(0, 0)
                .fotorama(),
              fotorama = $fotorama.data('fotorama');

            for (var _i = 0, _l = fotorama.data.length; _i < _l; _i++) {
                // prepare id to use in fotorama.show()
                fotorama.data[_i].id = fotorama.data[_i].img;
            }

            // bind clicks
            $thumbs.on('click', 'a', function (e) {
                e.preventDefault();

                var $this = $(this);

                $overlay
                  .show()
                  .stop()
                  .fadeTo(150, 1, function () {
                      $fotorama.stop().fadeTo(150, 1);

                      // API calls
                      fotorama
                          // show needed frame
                        .show({index: $this.attr('href'), time: 0})
                          // open fullscreen
                        .requestFullScreen();
                  });
            });

            $fotorama.on('fotorama:fullscreenexit', function () {
                $fotorama.stop().fadeTo(0, 0);
                $overlay.stop().fadeTo(300, 0, function () {
                    $overlay.hide();
                });
            });
        });

    });
</script>
<script type="text/javascript">
    jQuery('.mpblog-post.mpblog-post-view .mp-content a img').click(function(){
        jQuery(".fotorama #fotorama-a").trigger('click');
    })
</script>