<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Smtp
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function checkConnection() {
        var elem = $('<?php echo $this->getHtmlId() ?>');

        params = {
            server:     $('amsmtp_smtp_server').value,
            port:       $('amsmtp_smtp_port').value,
            auth:       $('amsmtp_smtp_auth').value,
            login:      $('amsmtp_smtp_login').value,
            passw:      $('amsmtp_smtp_passw').value,
            security:   $('amsmtp_smtp_sec').value,
            test_email: $('amsmtp_smtp_test_email').value
        };

        new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function(response) {
                result = '<?php echo $this->__('Connection Failed!') ?>';
                try {
                    response = response.responseText;
                    if (response == 1) {
                        result = '<?php echo $this->__('Connection Successful!') ?>';
                        elem.removeClassName('fail').addClassName('success')
                    } else {
                        elem.removeClassName('success').addClassName('fail')
                    }
                } catch (e) {
                    elem.removeClassName('success').addClassName('fail')
                }
                $('validation_result').update(result);
            }
        });
    }
    //]]>
</script>
<button onclick="javascript:checkConnection(); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span id="validation_result"><?php echo $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>
