<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Mageplace_Flippingbook
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php if (count($this->getMagazines()) > 0): ?>
    <div class="more-views">
        <h2><?php echo $this->__('HTML5 Flipping Books') ?></h2>
        <ul>
            <?php foreach ($this->getMagazines() as $_magazine): ?>
                <li>
                    <?php if ($_magazine->getMagazineViewMode()): ?>
                        <a href="#" onclick="popWin('<?php echo $this->getMagazineUrl($_magazine) ?>', 'flippingbook', 'width=<?php echo $this->getPopupWidth($_magazine); ?>,height=<?php echo $this->getPopupHeight($_magazine); ?>'); return false;" title="<?php echo $this->htmlEscape($_magazine->getName()) ?>">
                    <?php else: ?>
                        <a href="<?php echo $this->getMagazineUrl($_magazine) ?>"
                           title="<?php echo $this->htmlEscape($_magazine->getName()) ?>">
                    <?php endif; ?>
                    <img src="<?php echo $_magazine->getThumbUrl(); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_magazine->getName()) ?>"/>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
