<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Scheckout
 */
?>
<?php
    $_field = $this->getField();
    $hlr = $this->helper("amscheckout");
    echo $hlr->getBeforeControlHtml($_field);
?>
<input type="text" id="<?php echo $this->getFieldId('customer_mobile')?>" name="<?php echo $this->getFieldName('customer_mobile')?>" value="<?php echo $this->escapeHtml($this->getObject()->getCustomerMobile()) ?>" title="<?php echo $this->getStoreLabel('customer_mobile') ?>" maxlength="255" class="input-text <?php echo $_field['field_required'] ? "required-entry" : "" ?>" <?php echo $this->getFieldParams() ?> />
<?php echo $hlr->getAfterControlHtml($_field);?>
