<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Scheckout
 */
?>
<?php
    $hlr = $this->helper("amscheckout");
    $messages = $hlr->getQuoteItemMessages($this->getItem());
?>
<?php $_item = $this->getItem()?>
<?php $product = $_item->getProduct();?>
<tr class="amscheckout-item">
    <td>
			<div class="opc-product-image">
				<?php if ($hlr->showThumbnail()):?>
					<img src="<?php  echo Mage::helper('catalog/image')->init($_item->getProduct(), 'thumbnail')->resize(100); ?>"/>
				<?php endif; ?>
			</div>
			<div class="opc-product-info">
        <div class="product-name"><?php echo $this->htmlEscape($this->getProductName()) ?></div>
        <?php if ($_options = $this->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->htmlEscape($_option['label']) ?><?php echo $this->__(':')?></dt>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif; ?>
            </dd>
            <?php endforeach; ?>
        </dl>
        <?php endif;?>
        <?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
				<?php /* Show price */ ?>
				<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<div class="opc-review-price">
							<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
									<span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
							<?php else: ?>
									<span class="cart-price">
							<?php endif; ?>

									<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
											<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
									<?php else: ?>
											<?php if($product->getFinalPrice() < $product->getPrice()): ?>
												<div class="price-box">
													<p class="special-price">
														<?php echo $this->helper('checkout')->formatPrice($product->getFinalPrice()); ?>
													</p>
													<p class="old-price">
														<?php echo $this->helper('checkout')->formatPrice($product->getPrice()); ?>
													</p>
												</div>
											<?php else: ?>
												<div class="price-box">
													<p class="regular-price">
														<?php echo $final_price = $this->helper('checkout')->formatPrice($product->getPrice()); ?>
													</p>
												</div>
											<?php endif; ?>
									<?php endif; ?>

							</span>


							<?php if (Mage::helper('weee')->getApplied($_item)): ?>

									<div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
											<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
													<small>
													<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
															<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
													<?php endforeach; ?>
													</small>
											<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
													<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
															<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
													<?php endforeach; ?>
											<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
													<small>
													<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
															<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
													<?php endforeach; ?>
													</small>
											<?php endif; ?>
									</div>

									<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
											<div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
													<span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
											</div>
									<?php endif; ?>
							<?php endif; ?>
					</div>
					<?php endif; ?>
					<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<div>
							<?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
							<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
									<span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
							<?php else: ?>
									<span class="cart-price">
							<?php endif; ?>

									<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
											<?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
									<?php else: ?>
											<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
									<?php endif; ?>

							</span>
							<?php if (Mage::helper('weee')->getApplied($_item)): ?>

									<div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
											<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
													<small>
													<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
															<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span><br />
													<?php endforeach; ?>
													</small>
											<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
													<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
															<span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></small></span><br />
													<?php endforeach; ?>
											<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
													<small>
													<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
															<span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span><br />
													<?php endforeach; ?>
													</small>
											<?php endif; ?>
									</div>

									<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
											<div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
													<span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
											</div>
									<?php endif; ?>
							<?php endif; ?>
					</div>
				<?php endif; ?>
				<?php /* Show quantity */?>
				<div class="review-checkout-item-qty">
				<?php if ($this->helper("amscheckout")->isShoppingCartOnCheckout() && $this->helper("amscheckout")->isMergeShoppingCartCheckout()) { ?>
					<input id="review-qty" class="input-text input-qty" name="review[<?php echo $_item->getId(); ?>][qty]" type="text" value="<?php echo $_item->getQty() ?>"/>
        <?php } else { ?>
					<input id="review-qty" class="input-text input-qty" disabled="disabled" name="review[<?php echo $_item->getId(); ?>][qty]" type="text" value="<?php echo $_item->getQty() ?>"/>
        <?php }?>
				</div>
			</div>
<?php foreach ($messages as $message): ?>
        <p class="item-msg opc-product-info <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']) ?></p>
<?php endforeach; ?>
	</td>
</tr>