<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @author     cherdchai Hinjumpa , bugcherd@gmail.com   089-003-5240
 * @website   http://magentothai.wordpress.com/
 */
    $data= $this->getQuoteData() ;

?>

<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style='display: none'>
        <li>
        <div class="installment_pay">
            <p class="title">ผ่อนชำระด้วยบัตรเครดิต จากธนาคารต่างๆ ได้ดังนี้</p>
        <?php
        $CurrentAmount = (double)Mage::getSingleton('checkout/cart')->getQuote()->getGrandTotal();

        $JavaScriptList = "";
        $UserSelect = $this->htmlEscape($this->getInfoData('po_number'));

        //=> Filter Limited
        $LoopNo = 1;
        $cartcondition = true;
        $AvaliableArray = array();
        $storeId = Mage::app()->getStore()->getStoreId();
        $session= Mage::getSingleton('checkout/session');


        $Debug =  Mage::getStoreConfigFlag('payment/KSmartpay/debug', $storeId);
        $PaymentPlanList = Mage::getStoreConfig('payment/KSmartpay/paymentcode', $storeId);
        $PaymentPlanListArray = array();
        $PaymentPlanListArray = explode(",", $PaymentPlanList);

        foreach($session->getQuote()->getAllItems() as $item)
        {

           $productsku = $item->getSku();
           $productname = $item->getName();
           $productqty = $item->getQty();
           $ItemRowPrice = $item->getRowTotal();
           $ItemCount = 0;

           if (($ItemRowPrice > 0) && ($cartcondition == true)) {
                $ItemCount++;
                $productid = $item->getProductId();
                //=> Get Attibute data
                $ProductInstallmentArray = array();
                $attributeValue = null;
                $attributeValue = "";
                $product = Mage::getModel('catalog/product')->load($productid);

                $PrdinstallmentsData = $product->getData('installments_attribute');

                if ($PrdinstallmentsData != "")  {
                    $PrdInstallmentArray = explode(",", $PrdinstallmentsData);
                    foreach ($PrdInstallmentArray as $PrdInstallmentItem) {
                        //=> Check x - Start
                        foreach ($PaymentPlanListArray as $PaymentPlanListItem) {
                            //=> Plan
                            if (Mage::getStoreConfigFlag('payment/'. trim($PaymentPlanListItem) .'/active', $storeId)) {
                                if (Mage::getStoreConfig('payment/'. trim($PaymentPlanListItem) .'/filterlimit', $storeId)==$PrdInstallmentItem) {
                                    $PlanActive = true;
                                    if (trim(Mage::getStoreConfig('payment/'. trim($PaymentPlanListItem) .'/min_order_total')) != "") {
                                        $PlanActive = $PlanActive && ($CurrentAmount >= (double)Mage::getStoreConfig('payment/'. trim($PaymentPlanListItem) .'/min_order_total'));
                                    }

                                    if (trim(Mage::getStoreConfig('payment/KSmartpay/max_order_total')) != "") {
                                        $PlanActive = $PlanActive && ($CurrentAmount <= (double)Mage::getStoreConfig('payment/'. trim($PaymentPlanListItem) .'/max_order_total'));
                                    }

                                    if ($PlanActive) {
                                        $ProductInstallmentArray[$PrdInstallmentItem] = trim($PaymentPlanListItem);
                                    }
                                }
                            }
                        }
                        //=> Check x - End
                    }
                    if ($LoopNo==1) {
                        $AvaliableArray = array_merge($AvaliableArray,$ProductInstallmentArray);
                    }
                    else {
                        $AvaliableArray = array_intersect($AvaliableArray,$ProductInstallmentArray);
                    }
                    if (count($AvaliableArray) < 1) {
                        $cartcondition = false;
                    }
                    //=> Loop Installment array
                    $LoopNo++;
                }
                else {
                    $cartcondition = false;
                }
                //=> End Product  - installments_attribute
            }
            // => (Price > 0) and (is Installment)
        }
        //=> Loop cart items
        
        
        if ($cartcondition==true) {
            if (count($AvaliableArray) < 1) {
                $cartcondition = false;
            }
        }
        if (!$cartcondition) {
            unset($AvaliableArray);
        }

        if (count($AvaliableArray)>0) {
            //=> Start List
            $InstallmentArray = array();
            $InstallmentZeroArray = array();
            foreach ($AvaliableArray as $PrdInstallmentItem) {
                $termMax = (int)Mage::getStoreConfig('payment/'. $PrdInstallmentItem .'/paymenttermmax', $storeId);
                $termRate = (double)Mage::getStoreConfig('payment/'. $PrdInstallmentItem .'/paymenttermrate', $storeId);
                if ($termRate>0) {
                    $InstallmentArray[$PrdInstallmentItem] = $termMax;
                }
                else {
                    $InstallmentZeroArray[$PrdInstallmentItem] = $termMax;
                }
            }
            //=> End List
        }

        //echo "<p>Installments Plan</p>";
        //print_r($AvaliableArray);

        //=> Sort by term
        arsort($InstallmentZeroArray);
        arsort($InstallmentArray);

        if ($Debug=="1") {
            echo "<!--";
            echo "<p>Zero Plan</p>";
            print_r($InstallmentZeroArray);
            echo "<p>Installments xxxx</p>";
            print_r($InstallmentArray);
            echo "-->";
        }

        $PlanNo = 1;
        $PlanDefaultKey = "";

        $ZeroMaxTerm = 0;
        $PlanZeroTitle = "";
        $PlanZeroArray = array();
        $InstallmentPlanName = "";
        $InstallmentBankName = "";

        if ((count($InstallmentZeroArray)>0) || (count($InstallmentArray)>0)) {
            //=> Rate 0%
            echo "<div class=\"choose_bank_pay clearfix\"><ul>";
            if (count($InstallmentZeroArray)>0) {
                foreach ($InstallmentZeroArray as $InstallmentKey => $InstallmentTerm) {
                    if ($PlanDefaultKey=="") {
                        $PlanDefaultKey =  $InstallmentKey;
                    }
                    $InstallmentPlanMaxTerm = $InstallmentTerm;
                    if ($ZeroMaxTerm < $InstallmentPlanMaxTerm) {
                        $ZeroMaxTerm = $InstallmentPlanMaxTerm;
                    }

                    if ($ZeroMaxTerm == $InstallmentPlanMaxTerm) {
                        $InstallmentBankName = Mage::getStoreConfig('payment/'. trim($InstallmentKey) .'/bank', $storeId);
                        if (!array_key_exists($InstallmentBankName,$PlanZeroArray)) {
                            $PlanZeroArray[$InstallmentBankName] = $InstallmentKey;
                        }
                    }

                    $InstallmentPlanName = Mage::getStoreConfig('payment/'. trim($InstallmentKey) .'/title', $storeId);
                    $InstallmentBankName = Mage::getStoreConfig('payment/'. trim($InstallmentKey) .'/bank', $storeId);
                    $terms = Mage::getStoreConfig('payment/'. trim($InstallmentKey) .'/paymentterms', $storeId);
                    echo "<li><input type=\"radio\" onclick=\"". trim($InstallmentKey) ."_click();\" name=\"payment[cc_owner]\"  id=\"installmentplan_". trim($InstallmentKey) ."\" value=\"". trim($InstallmentKey) ."\"" . (($PlanNo==1) ? " checked" : "") . "><div class=\"installmentplan_". trim($InstallmentKey) ."\"> ". $InstallmentPlanName ."</div></li>";
                    $JavaScriptList .= "function ". trim($InstallmentKey) ."_click() {";
                    $JavaScriptList .= "jQuery('#reccommend_bank').html('ผ่อน 0% กับ". $InstallmentBankName ."');" . PHP_EOL;
                    $JavaScriptList .= "jQuery('#installment_termno').children().remove();" . PHP_EOL;
                    if ($terms !="") {
                        $termArray = explode(",",$terms);
                        arsort($termArray);
                        foreach($termArray  as $key => $val) {
                            if ((int)$val>0) {
                                $JavaScriptList .= "jQuery('#installment_termno').append(jQuery('<option>', {value:'". trim($InstallmentKey) . "|" . $val ."', text:' ผ่อน " . $val . " เดือน เดือนละ " . number_format($CurrentAmount /  $val, 2, ".", ",") ."'}));" . PHP_EOL;
                            }
                        }
                    }
                    $JavaScriptList .= "} " . PHP_EOL;

                    $PlanNo ++;
                }
            }

            //=> Rate > 0
            if (count($InstallmentArray)>0) {

                foreach ($InstallmentArray as $InstallmentKey => $InstallmentTerm) {
                    if ($PlanDefaultKey=="") {
                        $PlanDefaultKey =  $InstallmentKey;
                    }
                    $InstallmentPlanName = Mage::getStoreConfig('payment/'. trim($InstallmentKey) .'/title', $storeId);
                    $InstallmentBankName = Mage::getStoreConfig('payment/'. trim($InstallmentKey) .'/bank', $storeId);
                    $terms = Mage::getStoreConfig('payment/'. trim($InstallmentKey) .'/paymentterms', $storeId);
                    $termRate = (double)Mage::getStoreConfig('payment/'. trim($InstallmentKey) .'/paymenttermrate', $storeId);
                    echo "<li><input type=\"radio\" onclick=\"". trim($InstallmentKey) ."_click();\" name=\"payment[cc_owner]\"  id=\"installmentplan_". trim($InstallmentKey) ."\" value=\"". trim($InstallmentKey) ."\"" . (($PlanNo==1) ? " checked" : "") . "><div class=\"installmentplan_". trim($InstallmentKey) ."\"> ". $InstallmentPlanName ."</div></li>";
                    $JavaScriptList .= "function ". trim($InstallmentKey) ."_click() {";
                    $JavaScriptList .= "jQuery('#reccommend_bank').html('ผ่อนกับ". $InstallmentBankName ."');" . PHP_EOL;
                    $JavaScriptList .= "jQuery('#installment_termno').children().remove();" . PHP_EOL;
                    if ($terms !="") {
                        $maxtemselect = "";
                        $termArray = explode(",",$terms);
                        arsort($termArray);
                        foreach($termArray  as $key => $val) {
                            if ((int)$val>0) {
                                $JavaScriptList .= "jQuery('#installment_termno').append(jQuery('<option>', {value:'". trim($InstallmentKey) . "|" . $val ."', text:' ผ่อน " . number_format($termRate, 2, ".", ",") . "% นาน " . $val . " เดือน เดือนละ " . number_format(($CurrentAmount /  $val) + ($CurrentAmount * ($termRate / 100)), 2, ".", ",") ."'}));" . PHP_EOL;
                                $maxtemselect = $val;
                            }
                        }

                        //$JavaScriptList .= "jQuery('#installment_termno').val($maxtemselect);" . PHP_EOL;


                    }
                    $JavaScriptList .= "} " . PHP_EOL;


                    $PlanNo ++;
                }

            }
            echo "</ul></div>";
        }

        //=> Recomment
        $PlanZeroTitle = "";
        $PlanZeroNo = 1;
        $ZeroCount = count($PlanZeroArray);
        if ($ZeroCount>0) {
          foreach ($PlanZeroArray as $InstallmentKey => $InstallmentTerm) {
            if ($PlanZeroNo==1) {
              $PlanZeroTitle .= $InstallmentKey;
            }

            $PlanZeroNo++;
          }
        }

        if ($PlanZeroTitle != "") {
            echo "<p class=\"reccommend_bank\" id=\"reccommend_bank\">ผ่อน 0% กับ ". $PlanZeroTitle ."</p>";
        }
        else {
            $PlanZeroTitle = "";
            $PlanZeroNo = 1;
            $ZeroCount = count($InstallmentArray);
            if ($ZeroCount>0) {
                foreach ($InstallmentArray as $InstallmentKey => $InstallmentTerm) {
                    if ($PlanZeroNo==1) {
                        $PlanZeroTitle .= $InstallmentKey;
                    }
                    $PlanZeroNo++;
                }
            }

            echo "<p class=\"reccommend_bank\" id=\"reccommend_bank\">ผ่อนกับ ". $PlanZeroTitle ."</p>";
        }
        //=> Select
        ?>
        ท่านสามารถเลือกจำนวนเดือนที่ต้องการผ่อนชำระได้
        <?php
        $terms = Mage::getStoreConfig('payment/'. $PlanDefaultKey .'/paymentterms', $storeId);
        $termRate = Mage::getStoreConfig('payment/'. trim($PlanDefaultKey) .'/paymenttermrate', $storeId);
        echo "<!--" . $termRate . "|" . $PlanDefaultKey . "|"  . $storeId . "-->";
        echo "<div class=\"input-box box-select\"><select name=\"payment[check_no]\" id=\"installment_termno\">";
        if ($terms !="") {
            $termArray = explode(",",$terms);
            arsort($termArray);
            foreach($termArray  as $key => $val) {
                if ((int)$val>0) {
                    if ($PlanZeroTitle == "") {
                        echo "<option value=\"" . $PlanDefaultKey . "|" . $val ."\"> ผ่อน " . $val . " เดือน เดือนละ " . number_format($CurrentAmount /  $val, 2, ".", ",") . "</option>";
                    }
                    else {
                        echo "<option value=\"" . $PlanDefaultKey . "|" . $val ."\"> ผ่อน  ". number_format($termRate, 2, ".", ",") . "% นาน " . number_format($val, 0, ".", ",") . " เดือน เดือนละ " . number_format(($CurrentAmount /  $val) + ($CurrentAmount *  ($termRate / 100)), 2, ".", ",") . "</option>";
                    }
                }
            }
        }
        echo "</select></div>";
        ?>
        </div>
        </li>
    </ul>
    <script type="text/javascript">
    <?php echo $JavaScriptList;?>
    </script>
</fieldset>
