<?php
$_helper           =  Mage::helper('catalogsearch');
$_value            = $_helper->getEscapedQueryText();
$_currentCategory  = Mage::getSingleton('core/app')->getRequest()->getParam('cat');
$_currentAttribute = Mage::getSingleton('core/app')->getRequest()->getParam('attr');
$_filterType       = $this->getFilterType();
$_url              = $this->getAjaxUrl();
?>
<form class="searchautocomplete UI-SEARCHAUTOCOMPLETE" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get"
  data-url="<?php echo $_url ?>"
  data-minchars="<?php echo Mage::getStoreConfig('searchautocomplete/general/min_chars') ?>"
  data-delay="<?php echo Mage::getStoreConfig('searchautocomplete/general/delay') ?>">
  <div class="nav">
    <?php if ($_filterType == 'category'): ?>
    <div class="nav-search-in">
      <span class="category-fake UI-CATEGORY-TEXT"><?php echo $this->__('All') ?></span>
      <span class="nav-down-arrow"></span>
      <select name="cat" class="category UI-CATEGORY">
        <option value="0"><?php echo $this->__('All') ?></option>
        <?php foreach ($this->getCategories() as $_category): ?>
        <option value="<?php echo $_category->getId() ?>" <?php if ($_currentCategory == $_category->getId()): ?>selected<?php endif ?>>
            <?php echo $_category->getName() ?>
        </option>
        <?php endforeach ?>
      </select>
    </div>
    <?php elseif ($_filterType == 'attribute'): ?>
      <div class="nav-search-in">
        <span class="category-fake UI-CATEGORY-TEXT"><?php echo $this->__('All') ?></span>
        <span class="nav-down-arrow"></span>
        <select name="attr" class="category UI-CATEGORY">
          <option value="0"><?php echo $this->__('All') ?></option>
          <?php foreach ($this->getAttributes() as $_code => $_name): ?>
          <option value="<?php echo $_code ?>" <?php if ($_currentAttribute == $_code): ?>selected<?php endif ?>>
            <?php echo $_name ?>
          </option>
          <?php endforeach ?>
        </select>
      </div>
    <?php endif ?>
    <div class="nav-input UI-NAV-INPUT" style="padding-left: 76px;">
      <input id="input-search" class="input-text UI-SEARCH" type="text" autocomplete="off" name="<?php echo $_helper->getQueryParamName() ?>" value="<?php echo $_helper->getEscapedQueryText() ?>" maxlength="<?php echo $_helper->getMaxQueryLength() ?>" placeholder="<?php echo $this->__(Mage::getStoreConfig('searchautocomplete/general/tip')) ?>" onfocus="this.placeholder = ''" title="<?php echo $this->__(Mage::getStoreConfig('searchautocomplete/general/tip')) ?>" />
    </div>
    <div class="searchautocomplete-loader UI-LOADER">
      <div id="g01"></div>
      <div id="g02"></div>
      <div id="g03"></div>
      <div id="g04"></div>
      <div id="g05"></div>
      <div id="g06"></div>
      <div id="g07"></div>
      <div id="g08"></div>
    </div>
    <div style="display:none" class="searchautocomplete-placeholder UI-PLACEHOLDER"></div>
  </div>
  <div class="nav-submit-button">
    <button type="submit" title="<?php echo $this->__('Go') ?>" class="button"><?php echo $this->__('Go') ?></button>
  </div>
  <div class="box-keyword box-mobile">
    <a class="close-box-search" href="javascript:void(0)" title="<?php echo $this->__('close') ?>"><?php echo $this->__('close') ?></a>
    <a class="clear-search" href="javascript:void(0)" title="<?php echo $this->__('clear') ?>"><?php echo $this->__('clear') ?></a>
    <label><?php echo $this->__('Keyword') ?></label>
    <?php
    $number_keyword = 10;
    $collection = Mage::getModel('catalogsearch/query')->getCollection();
    $collection->addFieldToFilter('is_active','1');
    $collection->addFieldToFilter('store_id', Mage::app()->getStore()->getId());
    $collection->getSelect()->order('popularity desc');
    $collection->getSelect()->limit($number_keyword);
    ?>
    <ul class="keys-list">
      <?php $i = 0;?>
      <?php foreach ($collection->getItems() as $item) : ?>
        <?php $i++;?>
        <li><a href="<?php echo Mage::getUrl('catalogsearch/result')?>?q=<?php echo $item->getQueryText() ?>"><?php echo ' '.trim($item->getQueryText(),' '); ?></a></li>
      <?php endforeach; ?>
    </ul>
  </div>
  <script>
  jQuery('.clear-search').click(
    function(){
        jQuery('#input-search').val('');
    });
  </script>
</form>