<?php
/**
 * @author MarginFrame Team
 * @copyright Copyright (c) 2015 MarginFrame (http://www.marginframe.com)
 * @package MarginFrame_Shopby
 */
?>
<div class="amshopby-featured-wrapper">
<?php foreach ($this->getItems() as $item):?>
    <a href="<?php echo $item->getUrl()?>">
    <?php if ($item->getImgBig()) : ?>
        <img class="amshopby-featured" alt="<?php echo $this->htmlEscape($item->getCurrentTitle())?>" src="<?php echo $item->getImgBig()?>" />
    <?php else: ?>
    <?php echo $this->htmlEscape($item->getCurrentTitle())?>
        <?php endif ?>
    </a>
<?php endforeach ?>
</div>