<?php
/**
 * @author MarginFrame Team
 * @copyright Copyright (c) 2015 MarginFrame (http://www.marginframe.com)
 * @package MarginFrame_Shopby
 */
?>
<?php $links = $this->getLinks() ?>
<?php if (count($links)): ?>
<div class="amshopby-links-wrapper clearer">
	<?php $i=0; foreach ($links as $link): ?>
		<?php if ($i++%6==0): ?>
			<ul>
		<?php endif ?>
			<li>
				<a href="<?php echo $link['url']?>" title="<?php echo $this->htmlEscape($link['title'])?>" >
					<img alt="<?php echo $this->htmlEscape($link['title'])?>" src="<?php echo $link['img']?>">
				</a>
			</li>
		<?php if ($i%6==0 || $i==count($links)): ?>
			</ul>
		<?php endif ?>	
	<?php endforeach ?>
</div>
<?php endif; ?>