<?php
/**
 * @author MarginFrame Team
 * @copyright Copyright (c) 2015 MarginFrame (http://www.marginframe.com)
 * @package MarginFrame_Shopby
 */
?>
<div class="ratings" style="display: inline-block;margin: 0px;padding: 0px;">
    <div class="rating-box" style="margin:0px;">
        <span class="rating" style="width:<?php echo ($this->getStar()*20);?>%;"></span>
    </div>
</div>
<span style="font-size: smaller">&amp; up</span>
