<?php
/**
 * @author MarginFrame Team
 * @copyright Copyright (c) 2015 MarginFrame (http://www.marginframe.com)
 * @package MarginFrame_Shopby
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php $_removeTxt = Mage::helper('catalog')->__('Remove This Item') ?>
<?php if (!empty($_filters)): ?>
	<div class="currently">
			<ol>
					<?php foreach ($_filters as $_filter):?>
							<li>
									<span class="label"><?php echo Mage::helper('catalog')->__($_filter->getName()) ?>:</span>
									<?php if ($_filter->hasData('children')): ?>
											<?php $i = 0; foreach ($_filter->getData('children') as $child): ?>
													<span class="multiselect-child">
															<?php echo $child['label']  ?>
															<?php if($i != (count($_filter->getData('children'))-1)):?>
																<?php echo $this->__(',')  ?>
															<?php endif;?>
													</span>
											<?php $i++; endforeach ?>
									<?php else: ?>
											<?php echo $_filter->getLabel() ?>
									<?php endif ?>
							</li>
					<?php endforeach; ?>
			</ol>
	</div>
<?php endif; ?>
