<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Mageplace_Flippingbook
 */
?>
<span class="widget flippingbook-widget-link-image">
	<a <?php echo $this->getLinkAttributes() ?>>
		<img src="<?php echo $this->getThumbUrl(); ?>" width="56" height="56" title="<?php echo $this->htmlEscape($this->getAnchorText()); ?>" alt="<?php echo $this->htmlEscape($this->getAnchorText()); ?>" />
	</a>
</span>
