<?php
$column = Mage_Wishlist_Block_Customer_Wishlist_Items::getColumns();
$customer = Mage::getSingleton('customer/session')->getCustomer();
    if($customer->getId()){
        $wishlist = Mage::getModel('wishlist/wishlist')->loadByCustomer($customer, true);
        $wishListItemCollection = $wishlist->getItemCollection();
        echo "<h3>My Wishlist</h3><br />";
        echo "<table >";
        echo "<tr style=\"background-color:#252525;color:#FFFFFF;\"><th></th><th>PRODUCTS</th><th>SKU</th><th>PRICE</th><th>SPECAL PRICE</th></tr>";
        foreach ($wishListItemCollection as $item)
        {
            Mage::log($item);
            echo "<tr>";
            for($i=0;$i<4;$i++){
                echo "<td >"."&nbsp;"."<br />";
                $item = Mage::getModel('catalog/product')->setStoreId($item->getStoreId())->load($item->getProductId());
                if ($item->getId()) :
                    ?>
                    <img src="<?php echo Mage::helper('catalog/image')->init($item, 'image')->resize(70,70); ?>" width="90" height="90" />
                <?php endif;
                echo  "</td>";
                echo  "<td >"."&nbsp;"."<br /><br /><br />".$item->getName()."</td>";
                echo  "<td >"."&nbsp;"."<br /><br /><br />".$item->getSku()."</td>";
                echo  "<td >"."&nbsp;"."<br /><br /><br />".$item->getPrice()."</td>";
                echo  "<td >"."&nbsp;"."<br /><br /><br />".$item->getFinalPrice()."</td>";
            }
            echo "</tr>";
        }
        echo "</table>";
    }
echo "<style>
table, td {
    border-bottom: 1px solid #c1c1c1;
}

table {
    border-collapse: collapse;
    width: 100%;
}
td {
    height: 110px;
}
th {
    height: 30px;
}
</style>";
?>