<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
<h3 class="mastercheckout-title">Controleer uw bestelling</h3>
<div class="innerblock">

	<div class="mastercheckout-blocks">
        <div class="mastercheckout_address" ><div class="inner"><h4><?php echo $this->__("Billing address")?></h4><?php echo $this->billingAddress()->format('html');?></div></div>
        <div class="mastercheckout_address" ><div class="inner"><h4><?php echo $this->__("Shipping address")?></h4><?php echo $this->shippingAddress()->format('html');?></div></div>
        <div class="mastercheckout_payment"><div class="inner">
            <h4 class="mastercheckout_payment_method_title" ><?php echo $this->__("Payment method")?></h4>
            <?php echo Mage::getSingleton('checkout/session')->getQuote()->getPayment()->getMethodInstance()->getTitle(); ?>
            </div>
        </div>
        <div class="mastercheckout_shippingmethod"><div class="inner">
            <h4 class="mastercheckout_shipping_method_title"><?php echo $this->__("Shipping method")?></h4>
            <?php echo Mage::getSingleton('checkout/session')->getQuote()->getShippingAddress()->getShippingDescription(); ?>
            </div>
        </div>
        <span class="clear"></span>
    </div>

    <table class="data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <thead>
            <tr>
                <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
                <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>

	jQuery(document).ready(function() {
	
		function equalHeight(group) {

		var tallest = 0;
		group.each(function() {
			var thisHeight = jQuery(this).height();
			if(thisHeight > tallest) {
				tallest = thisHeight;
			}
		});
		group.children('div').height(tallest);
		}
		
	equalHeight(jQuery(".mastercheckout-blocks"));

	});

</script>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        <p class="back-link"><a href="#" onclick="activate_step('payment','review'); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <p class="f-center"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder') ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>
