<dl class="sp-methods" id="checkout-payment-method-load" style="width: 232px;">
<?php
    $methods = $this->getMethods();
    $oneMethod = count($methods) <= 1;
?>
<?php
    foreach ($methods as $_method):
        $_code = $_method->getCode();
?>
    <br/>
    <div class="mastercheckout_steps" >
        <d
    <dt>
    <?php if(!$oneMethod): ?>
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
    <?php else: ?>
        <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
        <?php $oneMethod = $_code; ?>
    <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
    </dt></div>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
    <dd>
        <?php echo $html; ?>
    </dd>
    <?php endif; ?>
<?php endforeach; ?>
</dl>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
//<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
payment.init();
<?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
<?php endif; ?>
//]]>
</script>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function(){
        jQuery("#p_method_<?php echo Mage::getStoreConfig('mastercheckout/maingroup/paymentmethod'); ?>").attr("checked","checked");
    });
//]]>
</script>