<?php
/*
* Copyright (c) 2014 www.magebuzz.com
*/
?>
<?php
$block = $this->getBannerads();
$banners = $block->getImages();
$blockType = $block->getDisplayType();
$helper = Mage::helper('bannerads');
//$isShowTitle = $helper->getTitleBanners();
//$isShowDescription = $helper->getDescriptionBanners();
$isBlockIds = array();
$urlShow = Mage::getUrl('bannerads/reports/impression');
$urlClick = Mage::getUrl('bannerads/reports/click');
?>
<?php if ($banners->getSize() > 0): ?>
  <div class="wrap-bannerads">
    <!-- Display type Show all -->
    <?php if ($blockType == 1): ?>
      <div class="div-banner">
        <ul class="banner-carousel">
          <?php $i=0; foreach ($banners->getItems() as $banner): $i++;?>
            <?php $isBlockIds[] = $banner->getBannerId(); ?>
            <li
              <?php if ($block->getBlockMaxWidth()): ?>style="max-width:<?php echo $block->getBlockMaxWidth() ?>px" <?php endif; ?>>
              <a <?php if ($banner->getBannerUrl() != ''): ?> href="<?php echo $banner->getBannerUrl(); ?>"<?php endif ?>
                onclick="bannerClicks('<?php echo $urlClick; ?>','<?php echo $banner->getBannerId() ?>','<?php echo $block->getBlockId() ?>')">
                <img  src="<?php echo $helper->getBannerImage($banner->getBannerImage()); ?>" alt=""/>
              </a>
            </li>
          <?php endforeach ?>
        </ul>
        <script type="text/javascript">
//          Event.observe(window, 'load', function () {
//            var banner_ids = '<?php //echo implode(",", $isBlockIds); ?>//';
//            var block_id = '<?php //echo $block->getBlockId();?>//';
//            var imp_url = '<?php //echo $urlShow; ?>//';
//            new Ajax.Request(imp_url, {
//              method: 'post',
//              parameters: {banner_ids: banner_ids, block_id: block_id},
//              onFailure: '',
//              onSuccess: ''
//            });
//          });
        </script>
      </div>
    <?php endif ?>
    <!-- Display type random -->
    <?php if ($blockType == 2): ?>
      <div class="div-banner">
        <div class="banner"
             <?php if ($block->getBlockMaxWidth()): ?>style="max-width:<?php echo $block->getBlockMaxWidth() ?>px" <?php endif; ?>>
          <a <?php if ($banners->getBannerUrl() != ''): ?> href="<?php echo $banners->getBannerUrl(); ?>" <?php endif ?>
            onclick="bannerClicks('<?php echo $urlClick; ?>','<?php echo $banners->getBannerId() ?>','<?php echo $block->getBlockId() ?>')">
            <img src="<?php echo $helper->getBannerImage($banners->getBannerImage()); ?>"
                 alt="<?php echo $banners->getBannerTitle(); ?>"/>
            <?php $isBlockIds[] = $banners->getBannerId(); ?>
          </a>
        </div>
        <script type="text/javascript">
//          Event.observe(window, 'load', function () {
//            banner_ids = '<?php //echo implode(",", $isBlockIds); ?>//';
//            block_id = '<?php //echo $block->getBlockId();?>//';
//            imp_url = '<?php //echo $urlShow; ?>//';
//            new Ajax.Request(imp_url, {
//              method: 'post',
//              parameters: {banner_ids: banner_ids, block_id: block_id},
//              onFailure: '',
//              onSuccess: ''
//
//            });
//          });
        </script>
      </div>
    <?php endif ?>
    <!-- Display type Slider -->
    <?php if ($blockType == 3): ?>
      <div class="banner"
           <?php if ($block->getBlockMaxWidth()): ?>style="max-width:<?php echo $block->getBlockMaxWidth() ?>px" <?php endif; ?>>
        <ul class="banner-carousel-menu" id="banner_carousel_menu_<?php echo $block->getBlockId() ?>">
          <?php $i=0; foreach ($banners->getItems() as $banner): $i++;?>
            <li>
              <a <?php if ($banner->getBannerUrl() != ''): ?> href="<?php echo $banner->getBannerUrl(); ?>" <?php endif ?>
                onclick="bannerClicks('<?php echo $urlClick; ?>','<?php echo $banner->getBannerId() ?>','<?php echo $block->getBlockId() ?>')">
                <img  src="<?php echo $helper->getBannerImage($banner->getBannerImage()); ?>" alt=""/>
              </a>
            </li>
            <?php $isBlockIds[] = $banner->getBannerId(); ?>
          <?php endforeach ?>
        </ul>
      </div>
      <script type="text/javascript">
//        Event.observe(window, 'load', function () {
//        var banner_ids = '<?php //echo implode(",", $isBlockIds); ?>//';
//          var block_id = '<?php //echo $block->getBlockId();?>//';
//          var imp_url = '<?php //echo $urlShow; ?>//';
//          new Ajax.Request(imp_url, {
//            method: 'post',
//            parameters: {banner_ids: banner_ids, block_id: block_id},
//            onFailure: '',
//            onSuccess: ''
//          });
//        });
        
        <?php if ($i > 1): ?>
         jQuery('#banner_carousel_menu_<?php echo $block->getBlockId();?>').bxSlider({
          slideWidth:240,
          loop:false,
          mode: 'horizontal',
          controls: false,
          speed: <?php echo Mage::helper('bannerads')->getTransitionSpeed()*1000?>,
          preloadImages: 'visible',
          pager: true,
          captions: false
        });
      <?php endif; ?>
        
      </script>
    <?php endif ?>
    <div style="clear: both;"></div>
  </div>
<?php endif ?>