<?php
/*
* Copyright (c) 2015 www.magebuzz.com
*/
?>
<?php
$block = $this->getBannerads();
$banners = $block->getImages();
$blockType = $block->getDisplayType();
$helper = Mage::helper('bannerads');
$isBlockIds = array();
$urlShow = Mage::getUrl('bannerads/reports/impression');
$urlClick = Mage::getUrl('bannerads/reports/click');
?>
<?php if ($banners->getSize() > 0): ?>
  <div class="wrap-bannerads">
    <!-- Display type Show all -->
    <?php if ($blockType == 1): ?>
      <div class="div-banner">
        <ul class="banner-carousel">
          <?php $i=0; foreach ($banners->getItems() as $banner): $i++;?>
            <?php $isBlockIds[] = $banner->getBannerId(); ?>
            <li
              <?php if ($block->getBlockMaxWidth()): ?>style="max-width:<?php echo $block->getBlockMaxWidth() ?>px" <?php endif; ?>>
              <a <?php if ($banner->getTarget()): ?> target="_blank" <?php endif;?> <?php if ($banner->getBannerUrl() != ''): ?> href="<?php echo $banner->getBannerUrl(); ?>"<?php endif ?>>
                <img
                  alt="<?php echo $banner->getBannerTitle(); ?>"
                  src="<?php echo $helper->getBannerImage($banner->getBannerImage()); ?>"/>
              </a>
            </li>
          <?php endforeach ?>
        </ul>
      </div>
    <!-- Display type random -->
    <?php elseif ($blockType == 2): ?>
      <div class="div-banner">
				<?php $i=0; foreach ($banners->getItems() as $banner): $i++;?>
        <div class="banner"
             <?php if ($block->getBlockMaxWidth()): ?>style="max-width:<?php echo $block->getBlockMaxWidth() ?>px" <?php endif; ?>>
          <a <?php if ($banner->getTarget()): ?> target="_blank" <?php endif;?> <?php if ($banner->getBannerUrl() != ''): ?> href="<?php echo $banner->getBannerUrl(); ?>" <?php endif ?>>
            <img src="<?php echo $helper->getBannerImage($banner->getBannerImage()); ?>"
                 alt="<?php echo $banner->getBannerTitle(); ?>"/>
            <?php $isBlockIds[] = $banner->getBannerId(); ?>
          </a>
        </div>
				<?php endforeach ?>
      </div>
    <!-- Display type Slider -->
    <?php elseif (($blockType == 3) || ($blockType == 4) || ($blockType == 5) || ($blockType == 6)) : ?>
      <div class="banner"
           <?php if ($block->getBlockMaxWidth()): ?>style="max-width:<?php echo $block->getBlockMaxWidth() ?>px" <?php endif; ?>>
        <ul class="banner-carousel" id="banner_carousel_<?php echo $block->getBlockId() ?>">
          <?php $i=0; foreach ($banners->getItems() as $banner): $i++;?>
            <li>
              <a <?php if ($banner->getTarget()): ?> target="_blank" <?php endif;?> <?php if ($banner->getBannerUrl() != ''): ?> href="<?php echo $banner->getBannerUrl(); ?>" <?php endif ?>>
                <img alt="<?php echo $banner->getBannerTitle(); ?>" src="<?php echo $helper->getBannerImage($banner->getBannerImage()); ?>"/>
              </a>
							<?php echo $banner->getBannerDescription(); ?>
            </li>
            <?php $isBlockIds[] = $banner->getBannerId(); ?>
          <?php endforeach ?>
        </ul>
      </div>
			<?php if ($i > 1): ?>
      <script type="text/javascript">              
        jQuery(document).ready(function () {
          jQuery('#banner_carousel_<?php echo $block->getBlockId()?>').bxSlider({
            auto: true,
            <?php if (($blockType == 3) || ($blockType == 4)): ?>
            mode: 'horizontal',
            <?php elseif (($blockType == 5) || ($blockType == 6)): ?>
            mode: 'fade',
            <?php endif; ?>
            controls: true,
            speed: <?php echo Mage::helper('bannerads')->getTransitionSpeed()*1000?>,
            preloadImages: 'visible',
            pager: <?php if(Mage::helper('bannerads')->showSliderPager()):?> true<?php else:?> false<?php endif; ?>,
            captions: <?php if (($blockType == 4) || ($blockType == 6)) echo 'true'; else echo 'false'; ?>
          });
        });        
      </script>
			<?php endif; ?>
    <?php endif ?>
  <div style="clear: both;"></div>
  </div>
<?php endif; ?>