<div class="buttons-set" id="payment-buttons-container">
    <p class="back-link"><a href="#" onclick="activate_step('login','payment'); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button type="button" class="button" onclick="to_step_3()"><span><span><?php echo $this->__('Next') ?></span></span></button>
    <span class="please-wait" id="payment-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>


<script type="text/javascript">
//<![CDATA[
    var to_step_3 = function() {
        shippingMethod.save();
        payment.save();
    };
//]]>
    

</script>