<div class="buttons-set billing-buttons-width" id="billing-buttons-container ">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <button type="button" title="<?php echo $this->__('Next') ?>" class="button" onclick="to_step_2()"><span><span><?php echo $this->__('Next') ?></span></span></button>
    <span class="please-wait" id="billing-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>

<script type="text/javascript">
//<![CDATA[
    var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
    var billingForm = new VarienForm('co-billing-form');

    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function(event) {
            var billingRememberMe = $$('#billing-new-address-form li #remember-me-box');
            if(billingRememberMe.length > 0) {
                billingRememberMe = $(billingRememberMe[0].parentNode);
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe.hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe.show();
                }
            }
        });
    }
//]]>
</script>

<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
//]]>
</script>

<script type="text/javascript">
//<![CDATA[
    var to_step_2 = function() {
        checkout.setMethod('payment');
        billing.save();
        if (jQuery("#billing\\:use_for_shipping_no").attr('checked') == 'checked') {
        }
    };

    jQuery(document).ready(function() {
      if (jQuery("#billing\\:use_for_shipping_no").attr('checked') == 'checked') {
          $('checkout_shipping').show();
      }
    });
//]]>
</script>