<?php
$collections = Mage::helper('career')->getJob();
?>
<div class="page-title style2">
  <h1><?php echo $this->__('Career') ?> </h1>
</div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('career-top-info')->toHtml() ?>

<?php if (count($collections)): ?>
  <table class="job_list box-desktop" onscroll="">
    <thead>
    <tr>
      <th id="job_title">
        <span><?php echo $this->__('Job Title')?></span>
      </th>
      <th id="job_function">
        <span><?php echo $this->__('Job Function')?></span>
      </th>
      <th id="position">
        <span><?php echo $this->__('Position')?></span>
      </th>
      <th id="location">
        <span><?php echo $this->__('Location')?></span>
      </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($collections as $collection): ?>
      <tr>
        <td id="job_title">
          <a href='<?php echo $this->getUrl('*/*/application',array('id' => $collection->getData('job_id')));?>'><?php echo $collection->getData('title'); ?></a>
        </td>
        <td id="job_function">
          <?php echo $collection->getData('function'); ?>
        </td>
        <td id="position">
          <?php echo $collection->getData('position'); ?>
        </td>
        <td id="location">
          <?php echo $collection->getData('location'); ?>
        </td>
      </tr>
    <?php endforeach?>
    </tbody>
  </table>
  <ul class="job_list box-mobile">
    <?php foreach($collections as $collection): ?>
      <li class="job-item">
         <dl>
           <dt><?php echo $this->__('Job Title')?></dt>
           <dd><?php echo $collection->getData('title'); ?></dd>
           <dt><?php echo $this->__('Job Function')?></dt>
           <dd><?php echo $collection->getData('function'); ?></dd>
           <dt><?php echo $this->__('Position')?></dt>
           <dd><?php echo $collection->getData('position'); ?></dd>
           <dt><span><?php echo $this->__('Location')?></dt>
           <dd><?php echo $collection->getData('location'); ?></dd>
         </dl>
        <a class="button read-more" href='<?php echo $this->getUrl('*/*/application',array('id' => $collection->getData('job_id')));?>'><span><?php echo $this->__('Read more')?></span></a>
      </li>
    <?php endforeach?>
  </ul>
<?php else:?>
  <?php echo $this->__("There are no jobs yet."); ?>
<?php endif; ?>