<?php 
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2015 Amasty (https://www.amasty.com)
 * @package Amasty_Ajaxlogin
 */  
 ?>
<div class="account-login">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="amajaxlogin-login-form-popup">
			<div class="am-form-block">
				<ul class="am-form-list">
					<li>
							<label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
							<div class="input-box">
									<input type="text" onKeyPress="sendRequestByEnter(event)" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
							</div>
					</li>
					<li>
							<label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
							<div class="input-box">
									<input type="password" onKeyPress="sendRequestByEnter(event)" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
							</div>
					</li>
					<?php echo $this->getChildHtml('form.additional.info'); ?>
				</ul>
				<div class="am-password-login"><a onclick="AmAjaxLoginObj.forgotPassword();" class=""><?php echo $this->__('Forgot Your Password?') ?></a></div>
				<button type="button" onclick="AmAjaxLoginObj.loginFormId('amajaxlogin-login-form-popup');" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Login')) ?>" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
			</div>
    </form>
  
</div>
